Repository hubtype/botonic, pull requests merged in 2021-06, with the labels that each got.

#1465 Chore/botonic Developer Experience (DX)
  .gitignore
  packages/botonic-dx/README.md
  packages/botonic-dx/baseline/README.md
  packages/botonic-dx/baseline/babel.config.js
  packages/botonic-dx/baseline/jest.config.js
  packages/botonic-dx/baseline/tests/__mocks__/file-mock.js
  packages/botonic-dx/baseline/tsconfig.eslint.json
  packages/botonic-dx/baseline/tsconfig.json
  packages/botonic-dx/baseline/tsconfig.tests.json
  packages/botonic-dx/package.json
  packages/botonic-dx/sample-config/.eslintrc-ci.js
  packages/botonic-dx/sample-config/.eslintrc.js
  packages/botonic-dx/sample-config/jest.config.js
  packages/botonic-dx/sample-config/jest.setup.js
  packages/botonic-dx/sample-config/package.json
  packages/botonic-dx/sample-config/tsconfig.eslint.json
  packages/botonic-dx/sample-config/tsconfig.json
  packages/botonic-dx/sample-config/tsconfig.tests.json
  packages/botonic-eslint-config/README.md
  packages/botonic-eslint-config/package.json
Labels: documentation, size/L

#1591 Feat/manage entry convert field values
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/contentful/manage/contentful-api.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-entry.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
Labels: size/M

#1603 chore(botonic-plugin-dynamodb): Get AWS credentials from new Organization's secret and assume a role before use them #PLA-505
  .github/workflows/botonic-plugin-dynamo-tests.yml
  packages/botonic-plugin-dynamodb/tests/helpers/dynamo.ts
  packages/botonic-plugin-dynamodb/tests/infrastructure/dynamo.integration.test.ts
Labels: size/M

#1590 Contentful/Make acronyms agnostic to dots #CUS-271
  packages/botonic-plugin-contentful/src/nlp/keywords.ts
  packages/botonic-plugin-contentful/src/nlp/normalizer.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
  packages/botonic-plugin-contentful/tests/nlp/keywords.test.ts
  packages/botonic-plugin-contentful/tests/nlp/normalizer.test.ts
Labels: documentation, size/L

#1604 feat(nlp): main points to lib/index.js
  packages/botonic-nlp/package.json
Labels: size/XS

#1570 botonic Developer Experience (DX) 2/3
  packages/botonic-dx/.gitignore
  packages/botonic-dx/README.md
  packages/botonic-dx/baseline/babel.config.js
  packages/botonic-dx/baseline/prettier.config.js
  packages/botonic-dx/baseline/tsconfig.json
  packages/botonic-dx/baseline/tsconfig.tests.json
  packages/botonic-dx/package.json
  packages/botonic-dx/sample-config/.prettierrc.js
  packages/botonic-dx/sample-config/package.json
  packages/botonic-dx/sample-config/tsconfig.json
  packages/botonic-eslint-config/.gitignore
  packages/botonic-eslint-config/index.js
  packages/botonic-eslint-config/package.json
Labels: size/M

#1602 botonic Developer Experience (DX) 3/3
  .gitignore
  package-lock.json
  package.json
  packages/babel.config.js
  packages/botonic-dx/README.md
  packages/botonic-dx/package.json
  packages/botonic-dx/sample-config/package.json
  packages/botonic-dx/sample-config/tsconfig.eslint.json
  packages/botonic-dx/sample-config/tsconfig.tests.json
  packages/botonic-eslint-config/package.json
Labels: size/M

#1619 Lint/fix slow
  packages/botonic-cli/.eslintrc.js
  packages/botonic-cli/.eslintrc_slow.js
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/commands/login.ts
  packages/botonic-cli/src/commands/new.ts
  packages/botonic-cli/src/commands/train.ts
  packages/botonic-cli/src/interfaces.ts
  packages/botonic-cli/src/util/system.ts
  packages/botonic-nlp/src/dataset/entities-parser.ts
  packages/botonic-nlp/src/model/manager.ts
  packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/tests/embeddings/database/storage.test.ts
  packages/botonic-nlp/tests/helpers/tools-helper.ts
  packages/botonic-nlp/tests/model/model-manager.test.ts
  packages/botonic-nlp/tests/tasks/ner/models/bilstm-model.test.ts
  packages/botonic-plugin-contentful/src/cms/exceptions.ts
  packages/botonic-plugin-contentful/src/util/backoff.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
  packages/botonic-plugin-contentful/tests/tools/l10n/import-updater.test.ts
  packages/botonic-plugin-intent-classification/src/index.ts
  packages/botonic-plugin-intent-classification/tests/tsconfig.json
  packages/botonic-plugin-ner/tests/tsconfig.json
Labels: size/L

#1605 feat(nlp): bump alpha version
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/model/model-info.ts
  packages/botonic-nlp/src/model/model-selector.ts
  packages/botonic-plugin-intent-classification/package-lock.json
  packages/botonic-plugin-intent-classification/package.json
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
Labels: size/S

#1606 Core & React: Fix types
  packages/botonic-core/package.json
  packages/botonic-core/src/types/index.d.ts
  packages/botonic-react/src/components/index.d.ts
  packages/botonic-react/src/index.d.ts
Labels: size/S

#1626 doc(contentful): doc to add new model
  packages/botonic-plugin-contentful/README.md
  packages/botonic-plugin-contentful/src/cms/cms.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts
  packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts
  packages/botonic-plugin-contentful/src/manage-cms/fields.ts
Labels: size/M

#1620 Creation of botonic-plugin-google-translate #BOT-430
  packages/botonic-plugin-google-translate/README.md
  packages/botonic-plugin-google-translate/jest.config.js
  packages/botonic-plugin-google-translate/package-lock.json
  packages/botonic-plugin-google-translate/package.json
  packages/botonic-plugin-google-translate/src/access-token.ts
  packages/botonic-plugin-google-translate/src/google-translate-api-service.ts
  packages/botonic-plugin-google-translate/src/index.ts
  packages/botonic-plugin-google-translate/src/language-detector.ts
  packages/botonic-plugin-google-translate/src/options.ts
  packages/botonic-plugin-google-translate/tsconfig.eslint.json
  packages/botonic-plugin-google-translate/tsconfig.json
Labels: size/L

#1623 Remove language detection from NLP plugins #BOT-451
  packages/botonic-plugin-intent-classification/README.md
  packages/botonic-plugin-intent-classification/package-lock.json
  packages/botonic-plugin-intent-classification/package.json
  packages/botonic-plugin-intent-classification/src/index.ts
  packages/botonic-plugin-intent-classification/src/utils/locale-utils.ts
  packages/botonic-plugin-intent-classification/tests/utils/locale-utils.test.ts
  packages/botonic-plugin-ner/README.md
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/index.ts
  packages/botonic-plugin-ner/src/utils/locale-utils.ts
  packages/botonic-plugin-ner/tests/utils/locale-utils.test.ts
Labels: size/M

#1618 Upgrade typescript from 4.2.x to 4.3.x
  docs/website/package.json
  package.json
  packages/botonic-dx/package.json
  packages/botonic-plugin-nlu/package-lock.json
  packages/botonic-plugin-nlu/package.json
Labels: size/S

#1641 tests(plugin-intent-classification): tests added #BOT-457
  packages/botonic-plugin-intent-classification/tests/helper/constants-helper.ts
  packages/botonic-plugin-intent-classification/tests/helper/tools-helper.ts
  packages/botonic-plugin-intent-classification/tests/process/prediction-processor.test.ts
  packages/botonic-plugin-intent-classification/tests/process/text-processor.test.ts
Labels: size/L

#1624 feat(plugin-google-translate): Translation feature added
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/types/index.d.ts
  packages/botonic-plugin-google-translate/README.md
  packages/botonic-plugin-google-translate/package-lock.json
  packages/botonic-plugin-google-translate/package.json
  packages/botonic-plugin-google-translate/src/google-translate-api-service.ts
  packages/botonic-plugin-google-translate/src/index.ts
  packages/botonic-plugin-google-translate/src/language-detector.ts
  packages/botonic-plugin-google-translate/src/options.ts
  packages/botonic-plugin-google-translate/src/translator.ts
Labels: size/L

#1643 fix(contentful): marked 2.1.0 was not compatible with node 12
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/S

#1637 Feat/on-connection-change-listener
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/index.d.ts
  packages/botonic-react/src/webchat-app.jsx
Labels: size/S

#1640 feat(contentful): if memoization fails, don't cache the error
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/delivery/cache.ts
  packages/botonic-plugin-contentful/src/contentful/delivery/client-api.ts
  packages/botonic-plugin-contentful/src/util/exceptions.ts
  packages/botonic-plugin-contentful/tests/contentful/delivery/cache.test.ts
  packages/botonic-plugin-contentful/tests/contentful/delivery/mock-client.helper.ts
Labels: size/L

#1639 feat(contentful): memoizer #BOT-467
  packages/botonic-plugin-contentful/README.md
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/delivery/fallback-cache.ts
  packages/botonic-plugin-contentful/src/plugin.ts
  packages/botonic-plugin-contentful/src/tools/l10n/import-updater.ts
  packages/botonic-plugin-contentful/src/util/backoff.ts
  packages/botonic-plugin-contentful/src/util/memoizer.ts
  packages/botonic-plugin-contentful/tests/contentful/delivery/fallback-cache.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
  packages/botonic-plugin-contentful/tests/util/memoizer.test.ts
Labels: documentation, size/XL

#1647 feat(nlp): add supported languages #BOT-283
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/preprocess/engines/de/normalizer-de.ts
  packages/botonic-nlp/src/preprocess/engines/de/stemmer-de.ts
  packages/botonic-nlp/src/preprocess/engines/de/stopwords-de.ts
  packages/botonic-nlp/src/preprocess/engines/de/tokenizer-de.ts
  packages/botonic-nlp/src/preprocess/engines/fr/normalizer-fr.ts
  packages/botonic-nlp/src/preprocess/engines/fr/stemmer-fr.ts
  packages/botonic-nlp/src/preprocess/engines/fr/stopwords-fr.ts
  packages/botonic-nlp/src/preprocess/engines/fr/tokenizer-fr.ts
  packages/botonic-nlp/src/preprocess/engines/it/normalizer-it.ts
  packages/botonic-nlp/src/preprocess/engines/it/stemmer-it.ts
  packages/botonic-nlp/src/preprocess/engines/it/stopwords-it.ts
  packages/botonic-nlp/src/preprocess/engines/it/tokenizer-it.ts
  packages/botonic-nlp/src/preprocess/engines/normalizer.ts
  packages/botonic-nlp/src/preprocess/engines/ru/normalizer-ru.ts
  packages/botonic-nlp/src/preprocess/engines/ru/stemmer-ru.ts
  packages/botonic-nlp/src/preprocess/engines/ru/stopwords-ru.ts
  packages/botonic-nlp/src/preprocess/engines/ru/tokenizer-ru.ts
  packages/botonic-nlp/src/preprocess/engines/stemmer.ts
  packages/botonic-nlp/src/preprocess/engines/stopwords.ts
  packages/botonic-nlp/src/preprocess/engines/tokenizer.ts
  packages/botonic-nlp/tests/preprocess/engines/de/normalizer-de.test.ts
  packages/botonic-nlp/tests/preprocess/engines/de/stemmer-de.test.ts
  packages/botonic-nlp/tests/preprocess/engines/de/tokenizer-de.test.ts
  packages/botonic-nlp/tests/preprocess/engines/fr/normalizer-fr.test.ts
  packages/botonic-nlp/tests/preprocess/engines/fr/stemmer-fr.test.ts
  packages/botonic-nlp/tests/preprocess/engines/fr/tokenizer-fr.test.ts
  packages/botonic-nlp/tests/preprocess/engines/it/normalizer-it.test.ts
  packages/botonic-nlp/tests/preprocess/engines/it/stemmer-it.test.ts
  packages/botonic-nlp/tests/preprocess/engines/it/tokenizer-it.test.ts
  packages/botonic-nlp/tests/preprocess/engines/ru/normalizer-ru.test.ts
  packages/botonic-nlp/tests/preprocess/engines/ru/stemmer-ru.test.ts
  packages/botonic-nlp/tests/preprocess/engines/ru/tokenizer-ru.test.ts
Labels: size/L

#1648 Refactor(nlp): en & es preprocessing engines #BOT-472
  packages/botonic-nlp/src/preprocess/engines/en/normalizer-en.ts
  packages/botonic-nlp/src/preprocess/engines/en/stopwords-en.ts
  packages/botonic-nlp/src/preprocess/engines/es/normalizer-es.ts
  packages/botonic-nlp/src/preprocess/engines/es/stopwords-es.ts
  packages/botonic-nlp/src/preprocess/engines/es/tokenizer-es.ts
  packages/botonic-nlp/tests/preprocess/preprocessor.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/process/processor.test.ts
  packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
Labels: size/L

#1625 Contenful/handoff
  packages/botonic-plugin-contentful/src/cms/callback.ts
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/cms-error.ts
  packages/botonic-plugin-contentful/src/cms/cms-log.ts
  packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
  packages/botonic-plugin-contentful/src/cms/cms.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts
  packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts
  packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/content-delivery.ts
  packages/botonic-plugin-contentful/src/contentful/contents/button.ts
  packages/botonic-plugin-contentful/src/contentful/contents/callback-delivery.ts
  packages/botonic-plugin-contentful/src/contentful/contents/contents.ts
  packages/botonic-plugin-contentful/src/contentful/contents/handoff.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-entry.ts
  packages/botonic-plugin-contentful/src/manage-cms/fields.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/handoff.test.ts
Labels: size/XL

#1667 fix(contentful): use of 1st argument (file_to_import)
  packages/botonic-plugin-contentful/bin/import-contentful-models.sh
Labels: size/XS

#1651 feat(core): add optional timeout to getOpenQueues & storeCaseRating
  packages/botonic-core/src/handoff.js
  packages/botonic-core/src/types/handoff.d.ts
Labels: size/S
