Repository hubtype/botonic, pull requests merged in 2021-03, with the labels that each got.

#1342 Chore/fix telemetry
  docs/docs/getting-started.mdx
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/scripts/postinstall.js
  packages/botonic-cli/src/analytics/credentials-handler.ts
  packages/botonic-cli/src/analytics/telemetry.ts
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/commands/login.ts
  packages/botonic-cli/src/commands/logout.ts
  packages/botonic-cli/src/commands/new.ts
  packages/botonic-cli/src/commands/serve.ts
  packages/botonic-cli/src/commands/test.ts
  packages/botonic-cli/src/commands/train.ts
  packages/botonic-cli/src/constants.ts
  packages/botonic-cli/src/interfaces.ts
  packages/botonic-cli/src/util/environment-info.ts
  packages/botonic-cli/src/util/file-system.ts
  packages/botonic-cli/src/util/system.ts
  packages/botonic-cli/src/utils.ts
  packages/botonic-cli/tests/analytics/credentials-handler.test.ts
  packages/botonic-cli/tests/analytics/telemetry.test.ts
  packages/botonic-cli/tests/botonic-api-service.test.ts
  packages/botonic-cli/tests/commands/deploy.test.ts
  packages/botonic-cli/tests/commands/new.test.ts
  packages/botonic-cli/tests/util/file-system.test.ts
Labels: size/XXL

#1377 refactor(Preprocess): Engines use nlpjs package
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/index.ts
  packages/botonic-nlp/src/preprocess/engines/en/normalizer-en.ts
  packages/botonic-nlp/src/preprocess/engines/en/stemmer-en.ts
  packages/botonic-nlp/src/preprocess/engines/en/stopwords-en.ts
  packages/botonic-nlp/src/preprocess/engines/en/tokenizer-en.ts
  packages/botonic-nlp/src/preprocess/engines/es/normalizer-es.ts
  packages/botonic-nlp/src/preprocess/engines/es/stemmer-es.ts
  packages/botonic-nlp/src/preprocess/engines/es/stopwords-es.ts
  packages/botonic-nlp/src/preprocess/engines/es/tokenizer-es.ts
  packages/botonic-nlp/src/preprocess/engines/normalizer.ts
  packages/botonic-nlp/src/preprocess/engines/stemmer.ts
  packages/botonic-nlp/src/preprocess/engines/stopwords.ts
  packages/botonic-nlp/src/preprocess/engines/tokenizer.ts
  packages/botonic-nlp/src/preprocess/index.ts
  packages/botonic-nlp/src/preprocess/preprocessor.ts
  packages/botonic-nlp/src/preprocess/types.ts
  packages/botonic-nlp/tests/preprocess/engines/en/normalizer-en.test.ts
  packages/botonic-nlp/tests/preprocess/engines/en/stemmer-en.test.ts
  packages/botonic-nlp/tests/preprocess/engines/en/tokenizer-en.test.ts
  packages/botonic-nlp/tests/preprocess/engines/es/normalizer-es.test.ts
  packages/botonic-nlp/tests/preprocess/engines/es/stemmer-es.test.ts
  packages/botonic-nlp/tests/preprocess/engines/es/tokenizer-es.test.ts
  packages/botonic-nlp/tests/preprocess/vocabulary-generator.test.ts
Labels: documentation, size/XL

#1398 Fix/cli logout command
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-api-service.ts
Labels: size/S

#1360 fix(core/react): retrieve agent messages after connection loss and HubtypeService refactor
  packages/botonic-core/src/hubtype-service.js
  packages/botonic-react/src/components/message.jsx
  packages/botonic-react/src/index.d.ts
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webchat/index.d.ts
  packages/botonic-react/src/webchat/messages-reducer.js
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#1400 Chore/revert msgcomponents duplicates and bump react
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/messages-reducer.js
Labels: size/S

#1403 chore: disable codecov's comments in PRs #PLA-387
  codecov.yml
Labels: size/XS

#1376 docs: fix example and add info in readme
  .gitignore
  README.md
  docs/docs/components/components-multichannel.md
Labels: size/M

#1404 Chore/upgrade_deps.sh & update dependencies
  package-lock.json
  package.json
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  scripts/ci/upgrade-deps.sh
Labels: size/M

#1379 feat(cli): task flag in botonic train command
  packages/botonic-cli/src/commands/train.ts
  packages/botonic-cli/tests/commands/train.test.ts
Labels: documentation, size/L

#1392 feat(ner): model stored by locale
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
Labels: size/XS

#1393 feat(ner-plugin): Preprocess implemented
  packages/botonic-plugin-ner/src/preprocess/input-generator.ts
  packages/botonic-plugin-ner/tests/helper/constants-helper.ts
  packages/botonic-plugin-ner/tests/helper/tools-helper.ts
  packages/botonic-plugin-ner/tests/preprocess/input-generator.test.ts
Labels: documentation, size/L

#1394 feat(ner-plugin): Postprocess implemented
  packages/botonic-plugin-ner/src/postprocess/prediction-processor.ts
  packages/botonic-plugin-ner/tests/postprocess/prediction-processor.test.ts
Labels: documentation, size/M

#1333 chore(core): add typings for @botonic/core
  packages/.eslintrc.js
  packages/botonic-core/package.json
  packages/botonic-core/src/index.js
  packages/botonic-core/src/router.d.ts
  packages/botonic-core/src/router.js
  packages/botonic-core/src/router.test.js
  packages/botonic-core/src/types/constants.d.ts
  packages/botonic-core/src/types/core-bot.d.ts
  packages/botonic-core/src/types/debug/index.d.ts
  packages/botonic-core/src/types/debug/inspector.d.ts
  packages/botonic-core/src/types/handoff.d.ts
  packages/botonic-core/src/types/hubtype-service.d.ts
  packages/botonic-core/src/types/i18n.d.ts
  packages/botonic-core/src/types/index.d.ts
  packages/botonic-core/src/types/plugins.d.ts
  packages/botonic-core/src/types/router.d.ts
  packages/botonic-core/src/types/utils.d.ts
Labels: size/XL
