Repository hubtype/botonic, pull requests merged in 2021-08, with the labels that each got.

#1743 chore(contentful): downgrade escape-string-regexp to version 4.0.0
  packages/botonic-plugin-contentful/jest.config.js
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#1745 fix(intent/ner): fix tests after stopwords update
  packages/botonic-plugin-intent-classification/tests/process/text-processor.test.ts
  packages/botonic-plugin-ner/tests/process/text-processor.test.ts
Labels: size/S

#1742 feat(api): implement /users endpoint
  packages/botonic-api/package-lock.json
  packages/botonic-api/package.json
  packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
  packages/botonic-api/src/data-provider/index.ts
  packages/botonic-api/src/data-provider/local-data-provider.ts
  packages/botonic-api/src/rest/routes/events.ts
  packages/botonic-api/src/rest/routes/users.ts
  packages/botonic-api/src/rest/routes/validation/common.ts
  packages/botonic-api/src/rest/routes/validation/events.ts
  packages/botonic-api/src/rest/routes/validation/users.ts
Labels: size/L

#1746 feat(cli/pulumi): add deploy command to aws/hubtype to Botonic CLI
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/analytics/telemetry.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/commands/destroy.ts
  packages/botonic-cli/src/constants.ts
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
  packages/botonic-pulumi/src/pulumi-runner.ts
Labels: size/L

#1747 feat(api): add proper pagination to endpoints
  packages/botonic-api/src/rest/routes/events.ts
  packages/botonic-api/src/rest/routes/users.ts
  packages/botonic-api/src/rest/routes/validation/common.ts
  packages/botonic-api/src/rest/utils/paginator.ts
Labels: size/M

#1758 feat(pulumi): cache invalidations for updated static assets
  packages/botonic-pulumi/jest.config.js
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
  packages/botonic-pulumi/src/aws/cache-invalidator.ts
  packages/botonic-pulumi/src/aws/deployment-stacks.ts
  packages/botonic-pulumi/src/aws/rest-server.ts
  packages/botonic-pulumi/src/aws/static-webchat-contents.ts
  packages/botonic-pulumi/src/pulumi-runner.ts
  packages/botonic-pulumi/tests/detect-updated-objects.test.ts
  packages/botonic-pulumi/tsconfig.json
Labels: size/L

#1763 Fix/dx botonic app config
  packages/botonic-dx/botonic-app-config/webpack/api-ws.js
  packages/botonic-dx/package.json
Labels: size/XS

#1762 fix(pulumi): throw error when exceeding name chars threshold
  packages/botonic-pulumi/src/aws/deployment-stacks.ts
  packages/botonic-pulumi/src/aws/index.ts
  packages/botonic-pulumi/src/aws/websocket-server.ts
  packages/botonic-pulumi/src/index.ts
  packages/botonic-pulumi/src/pulumi-runner.ts
Labels: size/M

#1779 chore: fix issues in create-botonic-app template
  packages/botonic-api/src/rest/routes/bot-input.ts
  packages/create-botonic-app/package-lock.json
  packages/create-botonic-app/package.json
  packages/create-botonic-app/template/bot/package.json
  packages/create-botonic-app/template/bot/src/index.js
  packages/create-botonic-app/template/webchat/package.json
Labels: size/S

#1806 Refactor/migrate core to ts pt.1
  packages/botonic-core/.eslintrc.js
  packages/botonic-core/index.d.ts
  packages/botonic-core/package.json
  packages/botonic-core/src/constants.ts
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/debug/index.ts
  packages/botonic-core/src/debug/inspector.ts
  packages/botonic-core/src/errors.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/hubtype-service.ts
  packages/botonic-core/src/i18n.ts
  packages/botonic-core/src/index.ts
  packages/botonic-core/src/output-parser/index.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/src/plugins.ts
  packages/botonic-core/src/router.ts
  packages/botonic-core/src/utils.ts
  packages/botonic-core/tests/debug/inspector.test.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-core/tests/hubtype-service.test.ts
  packages/botonic-core/tests/router.test.ts
Labels: size/M

#1808 refactor: Migrate @botonic/core to TS pt.2
  packages/botonic-core/index.d.ts
  packages/botonic-core/package.json
  packages/botonic-core/src/constants.ts
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/debug/inspector.ts
  packages/botonic-core/src/errors.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/hubtype-service.ts
  packages/botonic-core/src/i18n.ts
  packages/botonic-core/src/index.ts
  packages/botonic-core/src/models/user.ts
  packages/botonic-core/src/plugins.ts
  packages/botonic-core/src/router.ts
  packages/botonic-core/src/types/constants.d.ts
  packages/botonic-core/src/types/core-bot.d.ts
  packages/botonic-core/src/types/debug/index.d.ts
  packages/botonic-core/src/types/debug/inspector.d.ts
  packages/botonic-core/src/types/handoff.d.ts
  packages/botonic-core/src/types/hubtype-service.d.ts
  packages/botonic-core/src/types/i18n.d.ts
  packages/botonic-core/src/types/index.d.ts
  packages/botonic-core/src/types/plugins.d.ts
  packages/botonic-core/src/types/router.d.ts
  packages/botonic-core/src/types/utils.d.ts
  packages/botonic-core/src/utils.ts
  packages/botonic-core/tests/debug/inspector.test.ts
  packages/botonic-core/tsconfig.json
Labels: size/XXL
