Repository hubtype/botonic, pull requests merged in 2021-09, with the labels that each got.

#1805 chore(dx): fix files to be published with botonic-dx
  packages/botonic-dx/package.json
  packages/botonic-dx/sample-config/package.json
Labels: size/S

#1822 ci: configure detect-secrets #PLA-673
  .pre-commit-config.yaml
  .secrets.baseline
Labels: size/L

#1826 chore(core): cjs and esm distribution of core, enable @botonic/core tree-shaking
  packages/botonic-core/package.json
  packages/botonic-core/tsconfig.esm.json
  packages/botonic-core/tsconfig.json
Labels: size/S

#1878 ci: do not fail even that publish test reports fails #PLA-719
  .github/workflows/botonic-cli-tests.yml
  .github/workflows/botonic-nlu-tests.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-intent-classification-tests.yml
  .github/workflows/botonic-plugin-ner-tests.yml
  .github/workflows/botonic-plugin-nlu-tests.yml
Labels: size/S

#1886 feat(plugin-contentful): add missing handoff ContentFieldTypes
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/contentful/manage/manage-entry.ts
  packages/botonic-plugin-contentful/src/manage-cms/fields.ts
  packages/botonic-plugin-contentful/src/util/backoff.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
Labels: size/M

#1889 Ci/clean false secrets #PLA-735
  .pre-commit-config.yaml
  .secrets.baseline
  docs/docs/plugins/plugin-dashbot.md
  docs/docs/plugins/plugin-dynamoDB.md
  docs/docs/plugins/plugin-inbenta.md
  docs/docs/plugins/plugin-watson.md
  packages/botonic-plugin-dashbot/README.md
  packages/botonic-plugin-dynamodb/README.md
  packages/botonic-plugin-inbenta/README.md
  packages/botonic-plugin-watson/README.md
Labels: size/L
