Repository hubtype/botonic, pull requests merged in 2021-07, with the labels that each got.

#1671 feat(react): add new <Raw> component
  packages/botonic-core/src/index.js
  packages/botonic-react/src/components/index.js
  packages/botonic-react/src/components/raw.jsx
  packages/botonic-react/src/constants.js
Labels: size/M

#1672 feat(pulumi): add pulumi package to handle 1.0 deployments
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
  packages/botonic-pulumi/src/aws/deployment-stacks.ts
  packages/botonic-pulumi/src/aws/dynamodb.ts
  packages/botonic-pulumi/src/aws/index.ts
  packages/botonic-pulumi/src/aws/nlp-models-bucket.ts
  packages/botonic-pulumi/src/aws/policies.ts
  packages/botonic-pulumi/src/aws/rest-server.ts
  packages/botonic-pulumi/src/aws/static-webchat-contents.ts
  packages/botonic-pulumi/src/aws/websocket-server-lambda.ts
  packages/botonic-pulumi/src/aws/websocket-server.ts
  packages/botonic-pulumi/src/index.ts
  packages/botonic-pulumi/src/pulumi-downloader.ts
  packages/botonic-pulumi/src/pulumi-runner.ts
  packages/botonic-pulumi/src/system-utils.ts
  packages/botonic-pulumi/tsconfig.json
Labels: size/XXL

#1642 Contentful/cache size limit
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/delivery/fallback-cache.ts
  packages/botonic-plugin-contentful/src/plugin.ts
  packages/botonic-plugin-contentful/src/util/cache.ts
  packages/botonic-plugin-contentful/src/util/memoizer.ts
  packages/botonic-plugin-contentful/src/util/objects.ts
  packages/botonic-plugin-contentful/tests/contentful/delivery/fallback-cache.test.ts
  packages/botonic-plugin-contentful/tests/util/cache.test.ts
  packages/botonic-plugin-contentful/tests/util/memoizer.test.ts
  packages/botonic-plugin-contentful/tests/util/objects.test.ts
Labels: documentation, size/L

#1380 docs: new entry about webchat connection and disconnection
  docs/docs/webchat/webchat-api.md
  docs/docs/webchat/webchat-connectivity.md
  docs/website/sidebars.json
Labels: size/M

#1670 chore(plugin-contentful): bump and publish 0.19.0-alpha.5 version
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/contentful/delivery/cache.ts
Labels: size/XS

#1649 Contentful/profiler
  docs/docs/components/components-message.md
  packages/botonic-core/src/types/core-bot.d.ts
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/cms-error.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/util/index.ts
  packages/botonic-plugin-contentful/src/util/measurer/node-performance-measurer.ts
  packages/botonic-plugin-contentful/src/util/measurer/performance-measurer.ts
  packages/botonic-plugin-contentful/src/util/measurer/web-performance-measurer.ts
  packages/botonic-plugin-contentful/src/util/profiler.ts
  packages/botonic-plugin-contentful/tests/contentful/performance.integration.test.ts
  packages/botonic-plugin-contentful/tests/util/arrays.test.ts
  packages/botonic-plugin-contentful/tests/util/profiler.test.ts
  packages/botonic-plugin-contentful/tsconfig.json
  packages/botonic-react/src/components/index.d.ts
  packages/botonic-react/src/index.d.ts
Labels: size/XL

#1709 Full stack/add botonic1.0 dx configs
  packages/botonic-dx/botonic-app-config/webpack/api-rest.js
  packages/botonic-dx/botonic-app-config/webpack/api-ws.js
  packages/botonic-dx/botonic-app-config/webpack/assets-loaders.js
  packages/botonic-dx/botonic-app-config/webpack/optimization.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/babel-loader.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/esbuild-loader.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/transpiling-loader.js
  packages/botonic-dx/botonic-app-config/webpack/webchat.js
  packages/botonic-dx/package.json
Labels: size/L

#1646 Full stack/chore(core): add data models for botonic 1.0
  packages/botonic-core/src/models/events/connections/index.ts
  packages/botonic-core/src/models/events/index.ts
  packages/botonic-core/src/models/events/message/buttons.ts
  packages/botonic-core/src/models/events/message/carousel.ts
  packages/botonic-core/src/models/events/message/custom.ts
  packages/botonic-core/src/models/events/message/element.ts
  packages/botonic-core/src/models/events/message/index.ts
  packages/botonic-core/src/models/events/message/location.ts
  packages/botonic-core/src/models/events/message/media.ts
  packages/botonic-core/src/models/events/message/replies.ts
  packages/botonic-core/src/models/events/message/text.ts
  packages/botonic-core/src/models/user.ts
Labels: size/L

#1730 Full stack: Persist user/events data in bot-input endpoint
  packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
  packages/botonic-api/src/data-provider/index.ts
  packages/botonic-api/src/data-provider/local-data-provider.ts
  packages/botonic-api/src/rest/routes/bot-input.ts
  packages/botonic-api/src/rest/routes/index.ts
Labels: size/L

#1722 feat(api): Implementation of events endpoints
  packages/botonic-api/package-lock.json
  packages/botonic-api/package.json
  packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
  packages/botonic-api/src/data-provider/index.ts
  packages/botonic-api/src/data-provider/local-data-provider.ts
  packages/botonic-api/src/rest/routes/bot-input.ts
  packages/botonic-api/src/rest/routes/events.ts
  packages/botonic-api/src/rest/routes/index.ts
  packages/botonic-api/src/rest/routes/validation/events.ts
Labels: size/XL

#1732 Full stack: Add providerId in User interface
  packages/botonic-core/src/models/user.ts
  packages/botonic-core/src/router.test.js
Labels: size/XS

#1702 Full stack/chore(api): add api package for botonic1.0
  packages/botonic-api/package-lock.json
  packages/botonic-api/package.json
  packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
  packages/botonic-api/src/data-provider/dynamodb-utils.ts
  packages/botonic-api/src/data-provider/index.ts
  packages/botonic-api/src/data-provider/local-data-provider.ts
  packages/botonic-api/src/rest/index.ts
  packages/botonic-api/src/rest/routes/bot-input.ts
  packages/botonic-api/src/rest/routes/events.ts
  packages/botonic-api/src/rest/routes/index.ts
  packages/botonic-api/src/rest/routes/users.ts
  packages/botonic-api/src/rest/routes/validation/events.ts
  packages/botonic-api/src/websocket/aws-websocket-server.ts
  packages/botonic-api/src/websocket/index.ts
  packages/botonic-api/src/websocket/local-websocket-server.ts
  packages/botonic-api/tsconfig.json
Labels: size/XXL

#1731 refactor(create-botonic-app): Export only the NodeApp in bot/src/index.js
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/create-botonic-app/template/api/src/rest/app.ts
  packages/create-botonic-app/template/bot/src/index.js
  packages/create-botonic-app/template/bot/src/nlp/data/en/business.order.status.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/business.product.search.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.farewell.bye.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.farewell.courtesy.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.greeting.courtesy.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.greeting.hi.yaml
  packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.thanks.yaml
  packages/create-botonic-app/template/bot/src/routes.js
Labels: size/L

#1738 feat(nlp): Train with Unbalanced classes
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/model/manager.ts
  packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
Labels: size/M

#1740 feat(contentful): add paging in searchByKeywords
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/cms-error.ts
  packages/botonic-plugin-contentful/src/cms/cms-log.ts
  packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
  packages/botonic-plugin-contentful/src/cms/cms.ts
  packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/search/keywords.ts
  packages/botonic-plugin-contentful/src/search/search-by-keywords.ts
  packages/botonic-plugin-contentful/src/search/search.ts
  packages/botonic-plugin-contentful/src/util/measurer/node-performance-measurer.ts
  packages/botonic-plugin-contentful/tests/search/search-by-keywords.test.ts
Labels: size/L
