Repository hubtype/botonic, pull requests merged in 2021-10, with the labels that each got.

#1900 Contentful: custom content model
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/cms/callback.ts
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/cms-error.ts
  packages/botonic-plugin-contentful/src/cms/cms-log.ts
  packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
  packages/botonic-plugin-contentful/src/cms/cms.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/content-delivery.ts
  packages/botonic-plugin-contentful/src/contentful/contents/custom.ts
  packages/botonic-plugin-contentful/src/tools/l10n/import-updater.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/custom.test.ts
Labels: size/L

#1920 Chore/publish version 0.19.1 alpha.1 of plugin contentful
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/tests/cms/cms-error.test.ts
  packages/botonic-plugin-contentful/tests/util/profiler.test.ts
Labels: size/XS

#1917 fix(plugin-contentful): remove DeliveryWithFollowUp from url, payload…
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/contents/handoff.ts
  packages/botonic-plugin-contentful/src/contentful/contents/payload.ts
  packages/botonic-plugin-contentful/src/contentful/contents/url.ts
Labels: size/M
