Repository hubtype/botonic, pull requests merged in 2021-05, with the labels that each got.

#1497 chore(contentful): escape-string-regexp 5.0 needs transpilation
  packages/botonic-plugin-contentful/jest.config.js
Labels: size/XS

#1498 Feat/create and delete entry
  packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts
  packages/botonic-plugin-contentful/src/manage-cms/fields.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms-error.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-context.ts
  packages/botonic-plugin-contentful/tests/tools/l10n/import-updater.test.ts
Labels: size/L

#1494 chore(eslint-config): turn jest/no-conditional-expect to warn
  packages/botonic-eslint-config/index.js
  packages/botonic-eslint-config/package.json
Labels: size/S

#1519 docs(plugin-text-classification): Plugin Documentation #BOT-372
  packages/botonic-plugin-text-classification/README.md
Labels: documentation, size/M

#1495 feat(plugin-text-classification): Text Classification Plugin implemented #BOT-344
  .github/workflows/botonic-plugin-text-classification-tests.yml
  .pre-commit-config.yaml
  codecov.yml
  packages/botonic-plugin-text-classification/README.md
  packages/botonic-plugin-text-classification/jest.config.js
  packages/botonic-plugin-text-classification/package-lock.json
  packages/botonic-plugin-text-classification/package.json
  packages/botonic-plugin-text-classification/src/constants.ts
  packages/botonic-plugin-text-classification/src/index.ts
  packages/botonic-plugin-text-classification/src/model/model-info.ts
  packages/botonic-plugin-text-classification/src/model/model-selector.ts
  packages/botonic-plugin-text-classification/src/model/text-classifier.ts
  packages/botonic-plugin-text-classification/src/process/prediction-processor.ts
  packages/botonic-plugin-text-classification/src/process/text-processor.ts
  packages/botonic-plugin-text-classification/src/types.ts
  packages/botonic-plugin-text-classification/src/utils/environment-utils.ts
  packages/botonic-plugin-text-classification/src/utils/locale-utils.ts
  packages/botonic-plugin-text-classification/tests/utils/locale-utils.test.ts
  packages/botonic-plugin-text-classification/tsconfig.eslint.json
  packages/botonic-plugin-text-classification/tsconfig.json
Labels: size/L

#1521 docs(plugin-ner): Plugin NER Documentation #BOT-322
  packages/botonic-plugin-ner/README.md
Labels: documentation, size/M

#1524 refactor(nlp): remove compile fron BotonicNer and BotonicTextClassifier #BOT-337
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Labels: size/M

#1523 refactor(nlp): Ner and Text Classification model layers renamed #BOT-381
  packages/botonic-nlp/src/tasks/ner/models/bilstm-model.ts
  packages/botonic-nlp/src/tasks/text-classification/models/constants.ts
  packages/botonic-nlp/src/tasks/text-classification/models/simple-nn.ts
Labels: size/M

#1520 chore(plugin-contentful): bump alpha
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#1529 refactor(nlp): Dataset module refactor #BOT-385
  packages/botonic-nlp/src/dataset/data-augmenter.ts
  packages/botonic-nlp/src/dataset/dataset.ts
  packages/botonic-nlp/src/dataset/entities-parser.ts
  packages/botonic-nlp/src/dataset/input-data-parser.ts
  packages/botonic-nlp/src/dataset/input-data-reader.ts
  packages/botonic-nlp/src/dataset/loader.ts
  packages/botonic-nlp/src/dataset/types.ts
  packages/botonic-nlp/src/tasks/ner/process/processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/processor.ts
  packages/botonic-nlp/tests/dataset/dataset.test.ts
  packages/botonic-nlp/tests/dataset/entities-parser.test.ts
  packages/botonic-nlp/tests/dataset/input-data-parser.test.ts
  packages/botonic-nlp/tests/dataset/input-data-reader.test.ts
  packages/botonic-nlp/tests/dataset/loader.test.ts
  packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/processor.test.ts
Labels: size/L

#1551 refactor(nlp): rename input class field to intent BOT-400
  packages/botonic-nlp/src/dataset/dataset.ts
  packages/botonic-nlp/src/dataset/input-data-parser.ts
  packages/botonic-nlp/src/dataset/input-data-reader.ts
  packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
  packages/botonic-nlp/src/tasks/intent-classification/models/simple-nn.ts
  packages/botonic-nlp/src/tasks/intent-classification/process/prediction-processor.ts
  packages/botonic-nlp/src/tasks/intent-classification/process/processor.ts
  packages/botonic-nlp/src/tasks/intent-classification/storage/types.ts
  packages/botonic-nlp/tests/dataset/dataset.test.ts
  packages/botonic-nlp/tests/dataset/input-data-parser.test.ts
  packages/botonic-nlp/tests/dataset/input-data-reader.test.ts
  packages/botonic-nlp/tests/helpers/constants-helper.ts
  packages/botonic-nlp/tests/helpers/data/buy-product.yaml
  packages/botonic-nlp/tests/helpers/data/return-product.yaml
  packages/botonic-nlp/tests/helpers/models/intent-classification/en/config.json
  packages/botonic-nlp/tests/helpers/tools-helper.ts
  packages/botonic-nlp/tests/tasks/intent-classification/botonic-intent-classifier.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/models/simple-nn.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/process/prediction-processor.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/process/processor.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/storage/config-storage.test.ts
  packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
Labels: size/L

#1552 refactor(plugin-intent-classification): Text Classification plugin to Intent Classification #BOT-398
  .github/workflows/botonic-plugin-intent-classification-tests.yml
  .pre-commit-config.yaml
  codecov.yml
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-plugin-intent-classification/README.md
  packages/botonic-plugin-intent-classification/jest.config.js
  packages/botonic-plugin-intent-classification/package-lock.json
  packages/botonic-plugin-intent-classification/package.json
  packages/botonic-plugin-intent-classification/src/constants.ts
  packages/botonic-plugin-intent-classification/src/index.ts
  packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts
  packages/botonic-plugin-intent-classification/src/model/model-info.ts
  packages/botonic-plugin-intent-classification/src/model/model-selector.ts
  packages/botonic-plugin-intent-classification/src/process/prediction-processor.ts
  packages/botonic-plugin-intent-classification/src/process/text-processor.ts
  packages/botonic-plugin-intent-classification/src/types.ts
  packages/botonic-plugin-intent-classification/src/utils/environment-utils.ts
  packages/botonic-plugin-intent-classification/src/utils/locale-utils.ts
  packages/botonic-plugin-intent-classification/tests/utils/locale-utils.test.ts
  packages/botonic-plugin-intent-classification/tsconfig.eslint.json
  packages/botonic-plugin-intent-classification/tsconfig.json
Labels: size/M

#1526 refactor(plugin-ner, plugin-text-classification): Update Plugins Imports #BOT-382
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-plugin-intent-classification/package-lock.json
  packages/botonic-plugin-intent-classification/package.json
  packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts
  packages/botonic-plugin-intent-classification/src/process/prediction-processor.ts
  packages/botonic-plugin-intent-classification/src/process/text-processor.ts
  packages/botonic-plugin-ner/src/model/model-info.ts
  packages/botonic-plugin-ner/src/model/ner.ts
  packages/botonic-plugin-ner/src/process/prediction-processor.ts
  packages/botonic-plugin-ner/src/process/text-processor.ts
  packages/botonic-plugin-ner/tests/helper/tools-helper.ts
  packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts
  packages/botonic-plugin-ner/tests/process/text-processor.test.ts
Labels: size/M

#1563 chore(plugin-ner): bump nlp alpha version
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
Labels: size/XS

#1553 refactor(cli): text-classification task renamed to intent-classification #BOT-399
  packages/botonic-cli/src/commands/train.ts
Labels: size/XS

#1564 Chore/update deps
  package-lock.json
  package.json
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/tsconfig.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  scripts/ci/upgrade-deps.sh
Labels: size/M

#1554 Fix/remove parent div of cover component #BOT-384
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/XS

#1566 Contentful/test robutstness
  packages/botonic-plugin-contentful/src/util/backoff.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
Labels: size/L

#1568 Refactor(nlp): NLP Tasks constructors refactored #BOT-329
  packages/botonic-nlp/src/tasks/index.ts
  packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/nlp-task-config.ts
  packages/botonic-nlp/tests/tasks/intent-classification/botonic-intent-classifier.test.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
Labels: size/L

#1569 refactor(nlp): Config Reorganization
  packages/botonic-nlp/src/model/manager.ts
  packages/botonic-nlp/src/storage/config-storage.ts
  packages/botonic-nlp/src/storage/constants.ts
  packages/botonic-nlp/src/storage/index.ts
  packages/botonic-nlp/src/storage/model-storage.ts
  packages/botonic-nlp/src/storage/types.ts
  packages/botonic-nlp/src/tasks/index.ts
  packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
  packages/botonic-nlp/src/tasks/intent-classification/index.ts
  packages/botonic-nlp/src/tasks/intent-classification/storage/config-storage.ts
  packages/botonic-nlp/src/tasks/intent-classification/storage/index.ts
  packages/botonic-nlp/src/tasks/intent-classification/storage/types.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/ner/index.ts
  packages/botonic-nlp/src/tasks/ner/storage/config-storage.ts
  packages/botonic-nlp/src/tasks/ner/storage/index.ts
  packages/botonic-nlp/src/tasks/ner/storage/types.ts
  packages/botonic-nlp/src/tasks/nlp-task-config.ts
  packages/botonic-nlp/tests/model/model-manager.test.ts
  packages/botonic-nlp/tests/storage/config-storage.test.ts
  packages/botonic-nlp/tests/storage/model-storage.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/botonic-intent-classifier.test.ts
  packages/botonic-nlp/tests/tasks/intent-classification/storage/config-storage.test.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/ner/process/prediction-processor.test.ts
  packages/botonic-nlp/tests/tasks/ner/storage/config-storage.test.ts
Labels: size/L

#1567 Fix(plugin-ner, plugin-intent-classification): fix imports to work with serve mode
  packages/botonic-nlp/package.json
  packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts
  packages/botonic-plugin-intent-classification/src/process/prediction-processor.ts
  packages/botonic-plugin-intent-classification/src/process/text-processor.ts
  packages/botonic-plugin-intent-classification/src/utils/environment-utils.ts
  packages/botonic-plugin-ner/src/process/prediction-processor.ts
  packages/botonic-plugin-ner/src/process/text-processor.ts
  packages/botonic-plugin-ner/src/utils/environment-utils.ts
Labels: size/M

#1586 fix(cli): pass -c flag to build command
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/commands/deploy.ts
Labels: size/S

#1565 Refactor/split manager contentful class
  packages/botonic-plugin-contentful/src/contentful/manage/manage-asset.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-entry.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.helper.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
Labels: size/XL

#1571 Feat/create and remove asset
  packages/botonic-plugin-contentful/src/contentful/manage/manage-asset.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts
  packages/botonic-plugin-contentful/src/manage-cms/fields.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms-error.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
  packages/botonic-plugin-contentful/tests/tools/l10n/import-updater.test.ts
Labels: size/L

#1574 Contentful/asset info
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/contentful/contents/asset.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-asset.ts
  packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms-error.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms.ts
  packages/botonic-plugin-contentful/tests/contentful/contentful.helper.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/asset.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.helper.ts
  packages/botonic-plugin-contentful/tests/tools/l10n/import-updater.test.ts
Labels: size/L

#1587 chore: set codecov github action version to v1 #PLA-499
  .github/workflows/botonic-cli-tests.yml
  .github/workflows/botonic-core-tests.yml
  .github/workflows/botonic-nlu-tests.yml
  .github/workflows/botonic-plugin-contentful-tests.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-dynamo-tests.yml
  .github/workflows/botonic-plugin-intent-classification-tests.yml
  .github/workflows/botonic-plugin-nlu-tests.yml
  .github/workflows/botonic-react-tests.yml
Labels: size/M

#1573 refactor(plugin-ner, plugin-intent-classification): modelsBaseUrl parameter added #BOT-414
  packages/botonic-plugin-intent-classification/src/index.ts
  packages/botonic-plugin-intent-classification/src/model/model-info.ts
  packages/botonic-plugin-intent-classification/src/model/model-selector.ts
  packages/botonic-plugin-intent-classification/src/options.ts
  packages/botonic-plugin-intent-classification/src/types.ts
  packages/botonic-plugin-intent-classification/src/utils/environment-utils.ts
  packages/botonic-plugin-ner/src/index.ts
  packages/botonic-plugin-ner/src/model/model-info.ts
  packages/botonic-plugin-ner/src/model/model-selector.ts
  packages/botonic-plugin-ner/src/options.ts
  packages/botonic-plugin-ner/src/types.ts
  packages/botonic-plugin-ner/src/utils/environment-utils.ts
Labels: size/L

#1588 Nlp/selector refactor
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/model/index.ts
  packages/botonic-nlp/src/model/model-info.ts
  packages/botonic-nlp/src/model/model-selector.ts
  packages/botonic-nlp/tests/helpers/constants-helper.ts
  packages/botonic-plugin-intent-classification/package-lock.json
  packages/botonic-plugin-intent-classification/package.json
  packages/botonic-plugin-intent-classification/src/constants.ts
  packages/botonic-plugin-intent-classification/src/index.ts
  packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts
  packages/botonic-plugin-intent-classification/src/model/model-info.ts
  packages/botonic-plugin-intent-classification/src/model/model-selector.ts
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/constants.ts
  packages/botonic-plugin-ner/src/index.ts
  packages/botonic-plugin-ner/src/model/model-info.ts
  packages/botonic-plugin-ner/src/model/model-selector.ts
  packages/botonic-plugin-ner/src/model/ner.ts
Labels: size/L
