Repository hubtype/botonic, pull requests merged in 2021-04, with the labels that each got.

#1401 refactor(plugin-watson): revive watson plugin with assistantV2
  packages/botonic-plugin-watson/README.md
  packages/botonic-plugin-watson/package-lock.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-plugin-watson/src/index.js
  packages/botonic-plugin-watson/src/watson-output-parser.js
Labels: documentation, size/L

#1396 feat(ner-plugin): BotonicPluginNer implemented
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/tsconfig.json
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/index.ts
  packages/botonic-plugin-ner/src/model/model-info.ts
  packages/botonic-plugin-ner/src/model/model-selector.ts
  packages/botonic-plugin-ner/src/model/ner.ts
  packages/botonic-plugin-ner/src/postprocess/prediction-processor.ts
  packages/botonic-plugin-ner/src/preprocess/input-generator.ts
  packages/botonic-plugin-ner/src/types.ts
  packages/botonic-plugin-ner/src/utils/environment-utils.ts
  packages/botonic-plugin-ner/src/utils/locale-utils.ts
  packages/botonic-plugin-ner/tests/helper/tools-helper.ts
  packages/botonic-plugin-ner/tsconfig.json
Labels: documentation, size/L

#1420 refactor(plugin-ner): Reorganize Processes
  packages/botonic-plugin-ner/src/model/ner.ts
  packages/botonic-plugin-ner/src/preprocess/input-generator.ts
  packages/botonic-plugin-ner/src/process/prediction-processor.ts
  packages/botonic-plugin-ner/src/process/text-processor.ts
  packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts
  packages/botonic-plugin-ner/tests/process/text-processor.test.ts
Labels: size/L

#1370 feat(core): improvements in HubtypeService
  packages/botonic-core/src/hubtype-service.js
  packages/botonic-core/src/hubtype-service.test.js
Labels: size/M

#1437 refactor(plugin-ner): Codifier replaced by LabelEncoder
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/process/text-processor.ts
  packages/botonic-plugin-ner/tests/helper/tools-helper.ts
Labels: size/S

#1433 feat(nlp): Text Classification - Models
  packages/botonic-nlp/src/tasks/text-classification/models/constants.ts
  packages/botonic-nlp/src/tasks/text-classification/models/simple-nn.ts
  packages/botonic-nlp/src/tasks/text-classification/models/types.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts
  packages/botonic-nlp/tests/tasks/text-classification/models/simple-nn.test.ts
Labels: size/L

#1435 feat(nlp): Text Classification - Storage
  packages/botonic-nlp/src/tasks/text-classification/storage/config-storage.ts
  packages/botonic-nlp/src/tasks/text-classification/storage/types.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/model/config.json
  packages/botonic-nlp/tests/tasks/text-classification/storage/config-storage.test.ts
Labels: size/M

#1436 doc(contentful): improved help doc on export CSV
  packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts
  packages/botonic-plugin-contentful/src/manage-cms/manage-cms.ts
  packages/botonic-plugin-contentful/src/tools/l10n/export-csv-for-translators.ts
  packages/botonic-plugin-contentful/src/tools/l10n/import-csv-from-translators.ts
Labels: size/S

#1405 chore(core/react): fix types distribution
  packages/botonic-core/package.json
  packages/botonic-react/package.json
Labels: size/XS

#1442 feat(nlp): Text Classification - PredictionProcessor
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/prediction-processor.test.ts
Labels: size/L

#1441 feat(nlp): Text Classification - Processor
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/types.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/model/config.json
  packages/botonic-nlp/tests/helpers/tasks/text-classification/tools-helper.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/prediction-processor.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/processor.test.ts
Labels: size/L

#1454 refactor(nlp): Text Classification task
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/src/tasks/text-classification/models/constants.ts
  packages/botonic-nlp/src/tasks/text-classification/models/simple-nn.ts
  packages/botonic-nlp/src/tasks/text-classification/models/types.ts
  packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/types.ts
  packages/botonic-nlp/src/tasks/text-classification/storage/config-storage.ts
  packages/botonic-nlp/src/tasks/text-classification/storage/types.ts
  packages/botonic-nlp/tests/dataset/loader.test.ts
  packages/botonic-nlp/tests/helpers/general-helper.ts
  packages/botonic-nlp/tests/helpers/tasks/ner/helper.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts
  packages/botonic-nlp/tests/helpers/tasks/text-classification/model/config.json
  packages/botonic-nlp/tests/helpers/tasks/text-classification/tools-helper.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/models/simple-nn.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/prediction-processor.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/processor.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/storage/config-storage.test.ts
Labels: size/L

#1417 Contentful/document
  packages/botonic-plugin-contentful/bin/migrations/content-types/carousel.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/daterange.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/document-image.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/queue.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/startup.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/text.ts
  packages/botonic-plugin-contentful/bin/migrations/content-types/url-image.ts
  packages/botonic-plugin-contentful/bin/migrations/factories.ts
  packages/botonic-plugin-contentful/bin/migrations/migrate_contents.sh
  packages/botonic-plugin-contentful/src/cms/callback.ts
  packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
  packages/botonic-plugin-contentful/src/cms/cms-error.ts
  packages/botonic-plugin-contentful/src/cms/cms-log.ts
  packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
  packages/botonic-plugin-contentful/src/cms/cms.ts
  packages/botonic-plugin-contentful/src/cms/contents.ts
  packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts
  packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts
  packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
  packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
  packages/botonic-plugin-contentful/src/contentful/contents/document.ts
  packages/botonic-plugin-contentful/src/contentful/contents/follow-up.ts
  packages/botonic-plugin-contentful/src/render/botonic-converter.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/document.test.ts
  packages/botonic-plugin-contentful/tests/render/botonic-converter.test.ts
  packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Labels: size/XL

#1455 style(core): remove RouteRequest type replace it with BotRequest
  packages/botonic-core/src/types/index.d.ts
Labels: size/XS

#1453 refactor(nlp): dataset processes refactored
  packages/botonic-nlp/src/dataset/dataset.ts
  packages/botonic-nlp/src/dataset/loader.ts
  packages/botonic-nlp/src/dataset/types.ts
  packages/botonic-nlp/src/preprocess/selection.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/src/utils/array-utils.ts
  packages/botonic-nlp/tests/dataset/dataset.test.ts
  packages/botonic-nlp/tests/dataset/loader.test.ts
  packages/botonic-nlp/tests/helpers/constants-helper.ts
  packages/botonic-nlp/tests/helpers/tasks/ner/helper.ts
  packages/botonic-nlp/tests/helpers/tools-helper.ts
  packages/botonic-nlp/tests/preprocess/selection.test.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Labels: size/L

#1456 refactor(nlp): Preprocessor
  packages/botonic-nlp/src/preprocess/preprocessor.ts
  packages/botonic-nlp/src/preprocess/types.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/tests/preprocess/preprocessor.test.ts
Labels: size/L

#1432 chore(eslint-config): shareable eslint config package
  packages/botonic-core/README.md
  packages/botonic-eslint-config/README.md
  packages/botonic-eslint-config/index-ci.js
  packages/botonic-eslint-config/index.js
  packages/botonic-eslint-config/package.json
Labels: documentation, size/L

#1466 refactor(nlp): Remove Getters & Setters #BOT-330
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Labels: size/M

#1469 test(contentful): simplify contents in test space
  packages/botonic-plugin-contentful/exports/contentful-export.json
  packages/botonic-plugin-contentful/tests/contentful/contents.test.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/carousel.test.ts
  packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts
  packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Labels: size/XXL

#1467 feat(nlp): importModel method #BOT-336
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/ner/models/types.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Labels: size/M

#1459 feat(nlp): Vocabulary class
  packages/botonic-nlp/src/dataset/dataset.ts
  packages/botonic-nlp/src/preprocess/vocabulary.ts
  packages/botonic-nlp/src/utils/array-utils.ts
  packages/botonic-nlp/tests/dataset/dataset.test.ts
  packages/botonic-nlp/tests/preprocess/vocabulary.test.ts
Labels: size/M

#1471 refactor(nlp, plugin-ner): Filter Neutral Entities #BOT-341
  packages/botonic-nlp/src/tasks/ner/process/prediction-processor.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/ner/process/prediction-processor.test.ts
  packages/botonic-plugin-ner/src/process/prediction-processor.ts
  packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts
Labels: size/M

#1464 refactor(nlp): IndexedItems Integration
  packages/botonic-nlp/src/dataset/dataset.ts
  packages/botonic-nlp/src/encode/indexed-items.ts
  packages/botonic-nlp/src/encode/label-encoder.ts
  packages/botonic-nlp/src/encode/one-hot-encoder.ts
  packages/botonic-nlp/src/preprocess/vocabulary-generator.ts
  packages/botonic-nlp/src/preprocess/vocabulary.ts
  packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
  packages/botonic-nlp/src/tasks/ner/process/processor.ts
  packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
  packages/botonic-nlp/src/tasks/text-classification/process/processor.ts
  packages/botonic-nlp/tests/encode/indexed-items.test.ts
  packages/botonic-nlp/tests/encode/label-encoder.test.ts
  packages/botonic-nlp/tests/encode/one-hot-codifier.test.ts
  packages/botonic-nlp/tests/helpers/tools-helper.ts
  packages/botonic-nlp/tests/preprocess/vocabulary-generator.test.ts
  packages/botonic-nlp/tests/preprocess/vocabulary.test.ts
  packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Labels: size/L

#1468 fix(nlp, plugin-ner): Processors fixed #BOT-340
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
  packages/botonic-nlp/src/tasks/ner/process/processor.ts
  packages/botonic-nlp/src/tasks/text-classification/process/processor.ts
  packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
  packages/botonic-nlp/tests/tasks/text-classification/process/processor.test.ts
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/process/text-processor.ts
  packages/botonic-plugin-ner/tests/helper/constants-helper.ts
  packages/botonic-plugin-ner/tests/helper/tools-helper.ts
  packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts
  packages/botonic-plugin-ner/tests/process/text-processor.test.ts
Labels: size/L

#1472 feat(plugin-text-classification): BotonicPluginTextClassification implementation #BOT-342
  packages/botonic-plugin-text-classification/jest.config.js
  packages/botonic-plugin-text-classification/package-lock.json
  packages/botonic-plugin-text-classification/package.json
  packages/botonic-plugin-text-classification/src/constants.ts
  packages/botonic-plugin-text-classification/src/index.ts
  packages/botonic-plugin-text-classification/src/model/model-selector.ts
  packages/botonic-plugin-text-classification/src/model/text-classifier.ts
  packages/botonic-plugin-text-classification/src/types.ts
  packages/botonic-plugin-text-classification/src/utils/locale-utils.ts
  packages/botonic-plugin-text-classification/tsconfig.eslint.json
  packages/botonic-plugin-text-classification/tsconfig.json
Labels: size/L

#1473 feat(plugin-text-classification): Plugin Utils implementation #BOT-343
  packages/botonic-plugin-text-classification/src/utils/environment-utils.ts
  packages/botonic-plugin-text-classification/src/utils/locale-utils.ts
  packages/botonic-plugin-text-classification/tests/utils/locale-utils.test.ts
Labels: size/M

#1474 feat(plugin-text-classification): Model Selector implementation #BOT-347
  packages/botonic-plugin-text-classification/src/index.ts
  packages/botonic-plugin-text-classification/src/model/model-info.ts
  packages/botonic-plugin-text-classification/src/model/model-selector.ts
Labels: size/M

#1496 refactor(plugin-ner): Cross-fetch used #BOT-357
  packages/botonic-plugin-ner/package-lock.json
  packages/botonic-plugin-ner/package.json
  packages/botonic-plugin-ner/src/model/model-info.ts
  packages/botonic-plugin-ner/src/model/ner.ts
Labels: size/S

#1476 feat(plugin-text-classification): TextClassifier implemented #BOT-349
  packages/botonic-plugin-text-classification/package-lock.json
  packages/botonic-plugin-text-classification/package.json
  packages/botonic-plugin-text-classification/src/model/model-info.ts
  packages/botonic-plugin-text-classification/src/model/text-classifier.ts
  packages/botonic-plugin-text-classification/src/process/prediction-processor.ts
  packages/botonic-plugin-text-classification/src/process/text-processor.ts
Labels: size/M

#1477 feat(plugin-text-classification): TextProcessor implemented #BOT-345
  packages/botonic-plugin-text-classification/src/process/text-processor.ts
Labels: size/S

#1478 feat(plugin-text-classification): PredictionProcessor implemented #BOT-346
  packages/botonic-plugin-text-classification/src/process/prediction-processor.ts
Labels: size/S

#1500 chore: update codecov's action version #PLA-442
  .github/workflows/botonic-cli-tests.yml
  .github/workflows/botonic-core-tests.yml
  .github/workflows/botonic-nlu-tests.yml
  .github/workflows/botonic-plugin-contentful-tests.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-dynamo-tests.yml
  .github/workflows/botonic-plugin-nlu-tests.yml
  .github/workflows/botonic-react-tests.yml
Labels: size/S

#1501 test(botonic): enable plugin-text-classification tests #BOT-363
  .github/workflows/botonic-plugin-text-classification-tests.yml
  .pre-commit-config.yaml
  codecov.yml
Labels: size/M
