Repository hubtype/botonic, pull requests merged in 2022-12, with the labels that each got.

#2288 Feature: Flag to enable has_sense detection on plugin-hubtype-babel
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-hubtype-babel/src/options.ts
Labels: size/M

#2285 feat(react): Wrap all message buttons into a div
  packages/botonic-react/src/components/message.jsx
Labels: size/XS

#2289 Feature: Add plugin options information #DAT-403
  packages/botonic-plugin-hubtype-babel/README.md
Labels: size/S

#2287 feat: be able to receive Forms in Botonic #PLA-1177
  packages/botonic-core/src/models/events/botonic-event.ts
  packages/botonic-core/src/models/events/message/form.ts
  packages/botonic-core/src/models/events/message/index.ts
  packages/botonic-core/src/models/events/message/message-event.ts
  packages/botonic-core/src/output-parser/factory.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/tests/parsing/form.test.tsx
Labels: size/M
