Repository hubtype/botonic, pull requests merged in 2022-01, with the labels that each got.

#2142 Chore/bump dev versions
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-server/package-lock.json
  packages/botonic-server/package.json
  packages/create-botonic-app/dev-template/package.json
  packages/create-botonic-app/package-lock.json
  packages/create-botonic-app/package.json
Labels: size/M

#2144 Fix/pin colors version
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/create-botonic-app/package-lock.json
  packages/create-botonic-app/package.json
  packages/create-botonic-app/template/package.json
Labels: size/M

#2187 feature(babel): Plugin Hubtype Babel #DAT-65
  packages/botonic-plugin-hubtype-babel/README.md
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-hubtype-babel/src/options.ts
  packages/botonic-plugin-hubtype-babel/tsconfig.base.json
  packages/botonic-plugin-hubtype-babel/tsconfig.esm.json
  packages/botonic-plugin-hubtype-babel/tsconfig.json
Labels: size/L, CDTI

#2127 Feat/add environment manager #FLO-107
  packages/botonic-plugin-contentful/src/contentful/manage/manage-environment.ts
  packages/botonic-plugin-contentful/tests/contentful/contentful.helper.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-environment.ts
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.helper.ts
Labels: size/L
