Repository hubtype/botonic, pull requests merged in 2022-02, with the labels that each got.

#2201 feat(babel): Adapt Botonic Babel plugin to multiple intents #DAT-87
  packages/botonic-plugin-hubtype-babel/README.md
  packages/botonic-plugin-hubtype-babel/src/index.ts
Labels: size/S, CDTI

#2204 docs(Babel): bump babel plugin version
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/XS

#2202 fix: allow secret explicitly
  .secrets.baseline
  packages/botonic-core/src/hubtype-service.ts
Labels: size/S

#2218 feat(core): Allow to set an auto idle message in Handoff Builder
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/tests/handoff.test.ts
Labels: size/S

#2219 feat(react): Allow user input preprocess in blockInputs
  packages/botonic-core/src/core-bot.ts
  packages/botonic-react/src/components/index.d.ts
  packages/botonic-react/src/index.d.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2220 feat(react): Add class names to buttons
  packages/botonic-core/src/pusher-utils.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/src/components/button.jsx
Labels: size/S
