Repository hubtype/botonic, pull requests merged in 2023-12, with the labels that each got.

#2686 Plugin-flow-builder: remove start_up_node
  package-lock.json
  package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/start.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/M

#2687 Plugin hubtype babel: read HUBTYPE_API_URL from process.env
  packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-hubtype-babel/src/options.ts
Labels: size/S

#2693 Plugin Hubtype Analytics: Fix typo + Add Github Action and pre-commit execution
  .pre-commit-config.yaml
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
Labels: size/M

#2697 Plugin flow builder: fix typo
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/action/tracking.ts
Labels: size/XS

#2694 Plugin flow builder: open user input in webchat when do handoff
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-react/src/webchat/hooks/use-typing.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/M
