Repository hubtype/botonic, pull requests merged in 2023-05, with the labels that each got.

#2387 [Snyk] Upgrade concurrently from 6.2.1 to 6.5.1
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2388 [Snyk] Upgrade semver from 7.3.5 to 7.3.8
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2389 [Snyk] Upgrade tar from 6.1.11 to 6.1.13
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2390 [Snyk] Upgrade mime from 2.5.2 to 2.6.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2391 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.306.0 to 3.309.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2386 Botonic doc: Updating clients that use it
  docs/docs/welcome.md
Labels: size/S

#2403 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.309.0 to 3.312.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2404 [Snyk] Upgrade @aws-sdk/types from 3.306.0 to 3.310.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2405 [Snyk] Upgrade semver from 7.3.8 to 7.4.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2407 Botonic - Improve documentation (website)
  docs/docs/deployment/hubtype.md
  docs/docs/getting-started.mdx
  docs/docs/project-structure.md
  docs/src/components/examples.js
  docs/src/css/custom.css
  docs/src/pages/examples/index.js
Labels: size/L

#2417 fix: when the same attachment is uploaded twice, the second one will not trigger the onChange event
  packages/botonic-react/src/webchat/components/attachment.jsx
Labels: size/S

#2401 botonic improvements
  .github/workflows/botonic-core-tests.yml
  .github/workflows/botonic-react-tests.yml
  packages/botonic-core/jest.config.js
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/src/routing/router.ts
  packages/botonic-core/tsconfig.json
  packages/botonic-react/.eslintrc.js
  packages/botonic-react/babel.config.js
  packages/botonic-react/jest.config.js
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/index.js
  packages/botonic-react/src/msg-to-botonic.jsx
  packages/botonic-react/src/util/error-boundary.jsx
  packages/botonic-react/src/util/webchat.js
  packages/botonic-react/src/webchat/webchat.jsx
  packages/botonic-react/src/webview-app.tsx
  packages/botonic-react/tests/components/__snapshots__/custom-message.test.jsx.snap
  packages/botonic-react/tests/components/components.test.jsx
  packages/botonic-react/tests/components/custom-message.test.jsx
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-button.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/facebook/facebook.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-button.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-carousel-multibutton.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-carousel.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-reply.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-wrapper.test.jsx
  packages/botonic-react/tests/components/render-markdown.test.jsx
  packages/botonic-react/tests/components/text-serialization.test.jsx
  packages/botonic-react/tests/components/text.test.jsx
  packages/botonic-react/tests/helpers/test-utils.jsx
  packages/botonic-react/tests/webchat/attachments.test.js
  packages/botonic-react/tests/webchat/buttons-disabler.test.jsx
  packages/botonic-react/tests/webchat/dev-app.test.jsx
  packages/botonic-react/tests/webchat/storage.test.jsx
  packages/botonic-react/tests/webchat/usewebchat.test.js
  packages/botonic-react/tests/webchat/webchat-app.test.jsx
  packages/botonic-react/tests/webchat/webchat-util.test.js
  packages/botonic-react/tests/webchat/webchat.addmessages.test.jsx
  packages/botonic-react/tests/webchat/webchat.component.test.jsx
  packages/botonic-react/tsconfig.esm.json
  packages/botonic-react/tsconfig.json
Labels: size/XL

#2460 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.315.0 to 3.316.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2458 [Snyk] Upgrade aws-sdk from 2.1360.0 to 2.1362.0
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2466 [Snyk] Upgrade @botonic/core from 0.20.0 to 0.21.5
  packages/botonic-plugin-google-translation/package-lock.json
  packages/botonic-plugin-google-translation/package.json
Labels: size/XS

#2472 [Snyk] Upgrade aws-sdk from 2.1363.0 to 2.1364.0
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2473 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.316.0 to 3.319.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2468 Plugin flow builder: payloads
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/functions/index.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/S

#2463 Chore/improve tree shaking and update to React 17
  .github/workflows/botonic-docs-netlify-deploy.yml
  packages/botonic-react/jest.config.js
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/components/emoji-picker.jsx
  packages/botonic-react/src/webchat/hooks.js
  packages/botonic-react/src/webchat/use-storage-state-hook.js
  packages/botonic-react/src/webchat/webchat.jsx
  packages/botonic-react/tests/components/__snapshots__/custom-message.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/text.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel-multibutton.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
  packages/botonic-react/tests/webchat/__snapshots__/buttons-disabler.test.jsx.snap
  packages/botonic-react/tsconfig.esm.json
  packages/botonic-react/tsconfig.json
Labels: size/L

#2480 [Snyk] Upgrade aws-sdk from 2.1364.0 to 2.1365.0
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2488 feature(pluign-flow-builder): handoff payloads
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/flow-builder-models.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/M

#2494 feat: try to add bot-reviewer to botonic
  .github/workflows/pr.yml
Labels: size/S

#2496 refactor(react): fix index.d.ts types not being exported after migrating to typescript
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/botonic-tester.jsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/index.ts
  packages/botonic-react/src/components/multichannel/index-types.ts
  packages/botonic-react/src/components/multichannel/index.ts
  packages/botonic-react/src/contexts.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/index.d.ts
  packages/botonic-react/src/index.ts
  packages/botonic-react/src/message-utils.js
  packages/botonic-react/src/react-bot.jsx
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/index.ts
  packages/botonic-react/tests/msg-to-botonic.test.jsx
  packages/botonic-react/tests/utils.test.js
  packages/botonic-react/tests/webchat.theme.test.js
  packages/botonic-react/tsconfig.json
Labels: size/XL

#2502 Feat: use handoff auto assign prop on the flow builder #BLT-91
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/flow-builder-models.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
Labels: size/S

#2504 refactor(react): utils module to typescript
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/index.ts
  packages/botonic-react/src/util/index.d.ts
  packages/botonic-react/src/util/index.js
  packages/botonic-react/src/util/index.ts
Labels: size/S

#2500 Workflows: Create a reusable workflow for most flows #SER-2260
  .github/workflows/botonic-cli-tests.yml
  .github/workflows/botonic-common-workflow.yml
  .github/workflows/botonic-core-tests.yml
  .github/workflows/botonic-docs-netlify-deploy.yml
  .github/workflows/botonic-nlp-tests.yml
  .github/workflows/botonic-nlu-tests.yml
  .github/workflows/botonic-plugin-contentful-tests.yml
  .github/workflows/botonic-plugin-dashbot-tests.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-dynamo-tests.yml
  .github/workflows/botonic-plugin-google-analytics-tests.yml
  .github/workflows/botonic-plugin-inbenta-tests.yml
  .github/workflows/botonic-plugin-intent-classification-tests.yml
  .github/workflows/botonic-plugin-luis-tests.yml
  .github/workflows/botonic-plugin-ner-tests.yml
  .github/workflows/botonic-plugin-nlu-tests.yml
  .github/workflows/botonic-plugin-segment-tests.yml
  .github/workflows/botonic-plugin-watson-tests.yml
  .github/workflows/botonic-react-tests.yml
Labels: size/XL

#2507 chore: remove PR reviewer
  .github/workflows/pr.yml
Labels: size/S

#2506 feat(core): Don't execute bot when receiving a 'chatevent'
  package-lock.json
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/models/events/message/message-event.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/src/routing/router.ts
  packages/botonic-core/tests/routing/router.match-route.test.ts
  packages/botonic-core/tests/routing/router.misc.test.ts
Labels: size/M

#2508 Workflows Botonic: Documentation
  .github/workflows/README.md
  .github/workflows/botonic-cli-tests.yml
  .github/workflows/botonic-common-workflow.yml
  .github/workflows/botonic-core-tests.yml
  .github/workflows/botonic-docs-tests.yml
  .github/workflows/botonic-nlp-tests.yml
  .github/workflows/botonic-nlu-tests.yml
  .github/workflows/botonic-plugin-contentful-tests.yml
  .github/workflows/botonic-plugin-dashbot-tests.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-dynamo-tests.yml
  .github/workflows/botonic-plugin-google-analytics-tests.yml
  .github/workflows/botonic-plugin-inbenta-tests.yml
  .github/workflows/botonic-plugin-intent-classification-tests.yml
  .github/workflows/botonic-plugin-luis-tests.yml
  .github/workflows/botonic-plugin-ner-tests.yml
  .github/workflows/botonic-plugin-nlu-tests.yml
  .github/workflows/botonic-plugin-segment-tests.yml
  .github/workflows/botonic-plugin-watson-tests.yml
  .github/workflows/botonic-react-tests.yml
  .pre-commit-config.yaml
  .secrets.baseline
  package-lock.json
  scripts/qa/lint-botonic-package.sh
Labels: size/L

#2505 Plugin flow builder: tracking
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/M
