Repository hubtype/botonic, pull requests merged in 2023-09, with the labels that each got.

#2600 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.359.0 to 3.370.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2606 Botonic react: multichannel text use whatsapp button list
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/multichannel/index-types.ts
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/multichannel-utils.js
  packages/botonic-react/src/components/whatsapp-button-list.tsx
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
Labels: size/L

#2608 Botonic react: WebchatState and webchatContext with typescript
  packages/botonic-react/package-lock.json
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/contexts.jsx
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/actions.jsx
  packages/botonic-react/src/webchat/actions.ts
  packages/botonic-react/src/webchat/hooks.js
  packages/botonic-react/src/webchat/hooks/index.ts
  packages/botonic-react/src/webchat/hooks/use-component-visible.ts
  packages/botonic-react/src/webchat/hooks/use-component-will-mount.ts
  packages/botonic-react/src/webchat/hooks/use-previous.ts
  packages/botonic-react/src/webchat/hooks/use-typing.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/messages-reducer.ts
  packages/botonic-react/src/webchat/trigger-button/index.tsx
  packages/botonic-react/src/webchat/webchat-reducer.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/XL

#2614 Publish botonic react flow builder and knowledge bases
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/XS

#2534 Botonic Plugin Hubtype Analytics #SER-2379
  packages/botonic-plugin-hubtype-analytics/README.md
  packages/botonic-plugin-hubtype-analytics/package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-agent-rating.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-ai-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-faq.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-keyword-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-rating.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-channel-rating.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-faq-useful.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-fail.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-success.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tsconfig.esm.json
  packages/botonic-plugin-hubtype-analytics/tsconfig.json
Labels: size/XL

#2615 Botonic eslint and test configs: Modify packages to all be dependencies #SER-2762
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
Labels: size/S

#2619 Plugin Hubtype Analytics: fix get language typo
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-agent-rating.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
Labels: size/S

#2616 Plugin Hubtype Analytics: create knowledge base event
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-agent-rating.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowladge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
Labels: size/M

#2620 Feature: deploy bot in prod/qa/dev
  packages/botonic-core/src/hubtype-service.ts
  packages/botonic-core/src/utils.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
Labels: size/M

#2621 Plugin knowledge base: use external api
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-hubtype-analytics/package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/M

#2622 Fix: event bot_ai_knowledge_base fails
  packages/botonic-plugin-hubtype-analytics/package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
Labels: size/XS

#2613 Contentful Plugin: add content models with keywords to plugin options
  packages/botonic-plugin-contentful/jest.setup.js
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/cms/transform/message-content-filters.ts
  packages/botonic-plugin-contentful/src/cms/visitors/message-visitors.ts
  packages/botonic-plugin-contentful/src/contentful/contents/contents.ts
  packages/botonic-plugin-contentful/src/contentful/delivery-api.ts
  packages/botonic-plugin-contentful/src/contentful/delivery-utils.ts
  packages/botonic-plugin-contentful/src/contentful/ignore-fallback-decorator.ts
  packages/botonic-plugin-contentful/src/contentful/search/keywords.ts
  packages/botonic-plugin-contentful/src/contentful/traverser.ts
  packages/botonic-plugin-contentful/src/plugin.ts
  packages/botonic-plugin-contentful/src/tools/validate-all-contents.ts
  packages/botonic-plugin-contentful/tests/contentful/contents.test.ts
  packages/botonic-plugin-contentful/tests/contentful/delivery/mock-client.helper.ts
  packages/botonic-plugin-contentful/tests/nlp/keywords.test.ts
  packages/botonic-plugin-contentful/tests/util/profiler.test.ts
Labels: size/L

#2624 Publish new versions
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-hubtype-analytics/package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/S

#2625 docs(plugin-knowledge-bases): fix wrong npm package name
  packages/botonic-plugin-knowledge-bases/README.md
Labels: size/XS
