Repository hubtype/botonic, pull requests merged in 2023-04, with the labels that each got.

#2330 Botonic-dx: additional settings for bots libraries and testing #SER-1765
  packages/botonic-dx/baseline/jest.config.js
  packages/botonic-dx/package.json
Labels: size/S

#2306 Feat/botonic plugin analytics v4
  packages/botonic-plugin-google-analytics/README.md
  packages/botonic-plugin-google-analytics/package-lock.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-analytics/src/index.js
  packages/botonic-plugin-google-analytics/src/index.ts
  packages/botonic-plugin-google-analytics/src/types.ts
  packages/botonic-plugin-google-analytics/tsconfig.base.json
  packages/botonic-plugin-google-analytics/tsconfig.esm.json
  packages/botonic-plugin-google-analytics/tsconfig.json
Labels: size/L

#2332 feat: add support to close webviews in instagram #PLA-1688
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webview.jsx
Labels: size/S

#2302 feat(botonic-plugin-flow-builder): create new botonic-plugin-flow-builder package
  packages/botonic-plugin-flow-builder/README.md
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/content-fields-base.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-carousel.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-image.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/types.ts
  packages/botonic-plugin-flow-builder/src/flow-builder-models.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/functions/index.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
  packages/botonic-plugin-flow-builder/tsconfig.base.json
  packages/botonic-plugin-flow-builder/tsconfig.esm.json
  packages/botonic-plugin-flow-builder/tsconfig.json
Labels: size/XL

#2333 feat(plugin-flow-builder): keep adding plugin-flow-builder features
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/content-fields-base.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-video.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/types.ts
  packages/botonic-plugin-flow-builder/src/flow-builder-models.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/L

#2345 [Snyk] Upgrade @botonic/react from 0.21.0 to 0.21.2
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
Labels: size/XS

#2346 [Snyk] Upgrade axios from 1.3.3 to 1.3.4
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
Labels: size/XS

#2347 [Snyk] Upgrade aws-sdk from 2.1002.0 to 2.1347.0
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2349 [Snyk] Upgrade moment-timezone from 0.5.33 to 0.5.43
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2353 fix(react): lat, long to be numbers instead of strings
  docs/docs/components/components-location.md
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/location.jsx
Labels: size/M

#2359 [Snyk] Security upgrade aws-sdk from 2.1048.0 to 2.1354.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2362 [Snyk] Upgrade react-router-dom from 5.3.0 to 5.3.4
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/XS

#2364 fix(core): fix plugin types, allow to have plugins without pre/post, added new ResolvedPlugins type
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/plugins.ts
Labels: size/M

#2348 [Snyk] Upgrade contentful-import from 8.2.9 to 8.5.43
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/src/contentful/export/space-export.ts
  packages/botonic-plugin-contentful/src/typings.d.ts
Labels: size/S

#2371 feat(react): resolve assets automatically within components
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/audio.jsx
  packages/botonic-react/src/components/document.jsx
  packages/botonic-react/src/components/image.jsx
  packages/botonic-react/src/components/pic.jsx
  packages/botonic-react/src/components/video.jsx
  packages/botonic-react/src/util/environment.js
Labels: size/S

#2375 [Snyk] Upgrade html-entities from 2.3.2 to 2.3.3
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2376 [Snyk] Upgrade pako from 2.0.4 to 2.1.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2382 Feat/resolve static assets automatically
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/util/environment.js
Labels: size/M

#2378 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.30.0 to 3.306.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2380 [Snyk] Upgrade @vendia/serverless-express from 4.3.11 to 4.10.1
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2379 [Snyk] Upgrade @aws-sdk/types from 3.29.0 to 3.306.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2372 Botonic - Flow Builder Plugin: Add README file
  packages/botonic-plugin-flow-builder/README.md
Labels: size/L

#2383 feat(cli): create new bot when passing -b name
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/tsconfig.json
Labels: size/M
