Repository hubtype/botonic, pull requests merged in 2023-11, with the labels that each got.

#2631 Botonic DX: Bump prettier version #SER-2804
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
Labels: size/XS

#2650 feat(knowledge-bases): add question attribute in the response
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/XS

#2640 [Snyk] Security upgrade axios from 0.25.0 to 1.6.0
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/XS

#2663 Fallback logic on plugin-flow-builder
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
Labels: size/S

#2629 Tests @botonic/react with typescript
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/utils.ts
  packages/botonic-react/babel.config.js
  packages/botonic-react/jest.config.js
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/botonic-tester.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/message-utils.js
  packages/botonic-react/src/msg-to-botonic.jsx
  packages/botonic-react/src/react-bot.jsx
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webview-app.tsx
  packages/botonic-react/tests/components/components.test.jsx
  packages/botonic-react/tests/components/custom-message.test.jsx
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-button.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/facebook/facebook.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-button.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-carousel-multibutton.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-carousel.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-reply.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
  packages/botonic-react/tests/components/multichannel/multichannel-wrapper.test.jsx
  packages/botonic-react/tests/components/render-markdown.test.jsx
  packages/botonic-react/tests/components/text-serialization.test.jsx
  packages/botonic-react/tests/components/text.test.jsx
  packages/botonic-react/tests/helpers/test-utils.jsx
  packages/botonic-react/tests/msg-to-botonic.test.jsx
  packages/botonic-react/tests/utils.test.js
  packages/botonic-react/tests/webchat.theme.test.js
  packages/botonic-react/tests/webchat/attachments.test.js
  packages/botonic-react/tests/webchat/buttons-disabler.test.jsx
  packages/botonic-react/tests/webchat/dev-app.test.jsx
  packages/botonic-react/tests/webchat/storage.test.jsx
  packages/botonic-react/tests/webchat/usewebchat.test.jsx
  packages/botonic-react/tests/webchat/webchat-app.test.jsx
  packages/botonic-react/tests/webchat/webchat-util.test.js
  packages/botonic-react/tests/webchat/webchat.addmessages.test.jsx
  packages/botonic-react/tests/webchat/webchat.component.test.jsx
Labels: size/XL

#2630 Feat: increase the limit of contents in topContents method
  packages/botonic-plugin-contentful/src/contentful/contents/contents.ts
Labels: size/XS

#2668 Contentful plugin publish 0.23.1
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-environment.ts
  packages/botonic-plugin-contentful/tests/plugin.test.ts
Labels: size/S

#2666 Change message image when speaking with the bot or the agent
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-image.tsx
  packages/botonic-react/src/components/message/styles.ts
  packages/botonic-react/src/components/message/timestamps.jsx
  packages/botonic-react/src/components/timestamps.jsx
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/devices/device-adapter.js
Labels: size/L

#2667 Add css class in RepliesCopntainer
  packages/botonic-react/src/webchat/replies.jsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2672 Upgrade axios and publish new versions
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-plugin-dashbot/package-lock.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-google-analytics/package-lock.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package-lock.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package-lock.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package-lock.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package-lock.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package-lock.json
  packages/botonic-plugin-watson/package.json
Labels: size/M

#2670 Bot image or Agent image on MessageTimestamp component
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/message/message-image.tsx
  packages/botonic-react/src/components/message/styles.ts
  packages/botonic-react/src/components/message/timestamps.jsx
  packages/botonic-react/src/components/message/timestamps.tsx
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx
Labels: size/L

#2682 plugin-flow-builder: fix CORS error
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
Labels: size/XS
