Repository hubtype/botonic, pull requests merged in 2023-06, with the labels that each got.

#2526 Feat: add whatsapp button list in the flow builder plugin #BLT-73
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/whatsapp-button-list.ts
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-row.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-section.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/L

#2528 chore(react/core): Downgrade react to version 16 + bump package versions to 0.22.0
  package-lock.json
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/util/webchat.js
Labels: size/M

#2527 feature(botonic-cli): Bump version to 0.21.4 #PLA-20
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/analytics/credentials-handler.ts
  packages/botonic-cli/src/botonic-api-service.ts
Labels: size/M

#2531 Flow builder plugin: Fix url buttons + refactor
  .pre-commit-config.yaml
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-carousel.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/XL

#2533 chore: bump botonic flow builder plugin version to 0.22.3
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
Labels: size/XS

#2536 Flow builder refactor getContents, handoff and action
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/content-fields-base.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/handoff.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/L

#2538 [Snyk] Upgrade @pulumi/pulumi from 3.11.0 to 3.69.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2539 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.321.1 to 3.345.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2540 [Snyk] Upgrade @aws-sdk/types from 3.310.0 to 3.342.0
  packages/botonic-pulumi/package-lock.json
Labels: size/XS

#2542 [Snyk] Upgrade tar from 6.1.13 to 6.1.15
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2541 [Snyk] Upgrade @vendia/serverless-express from 4.10.1 to 4.10.4
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2544 [Snyk] Upgrade aws-sdk from 2.1376.0 to 2.1392.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2545 [Snyk] Upgrade html-entities from 2.3.3 to 2.3.5
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2546 [Snyk] Upgrade @babel/runtime from 7.21.0 to 7.22.3
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/XS
