Repository hubtype/botonic, pull requests merged in 2023-03, with the labels that each got.

#2308 fix: Webviews not redirecting correctly on WhatsApp Cloud #PLA-1598
  packages/botonic-react/src/webview.jsx
Labels: size/XS

#2307 feat(core): Add extra data field in HandoffBuilder
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/events/botonic-event.ts
  packages/botonic-core/src/models/events/message/index.ts
  packages/botonic-core/src/output-parser/factory.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/tests/handoff.test.ts
Labels: size/M

#2309 Botonic React: add user-input css class
  packages/botonic-react/src/webchat/components/emoji-picker.jsx
  packages/botonic-react/src/webchat/devices/scrollbar-controller.js
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2313 Plugin Flow Builder - Make handoff simpler
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/handoff.ts
Labels: size/M

#2312 feat(core): Add Contact Message Event type
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/events/message/contact.ts
  packages/botonic-core/src/models/events/message/message-event.ts
  packages/botonic-core/src/output-parser/factory.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/tests/parsing/contact.test.tsx
Labels: size/M

#2310 chore: bump core/react to 0.21.1 and plugin-contentful to 0.21.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/events/message/contact.ts
  packages/botonic-core/src/models/events/message/message-event.ts
  packages/botonic-core/src/output-parser/factory.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/tests/parsing/contact.test.tsx
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/M

#2314 Feat: custom user input buttons
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index.d.ts
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/webchat/components/attachment.jsx
  packages/botonic-react/src/webchat/components/common.jsx
  packages/botonic-react/src/webchat/components/conditional-animation.jsx
  packages/botonic-react/src/webchat/components/emoji-picker.jsx
  packages/botonic-react/src/webchat/components/persistent-menu.jsx
  packages/botonic-react/src/webchat/components/send-button.jsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2324 Fix/from scratch deploy
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/commands/deploy.ts
Labels: size/M
