Repository hubtype/botonic, pull requests merged in 2023-08, with the labels that each got.

#2590 [Snyk] Upgrade semver from 7.5.2 to 7.5.3
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2591 [Snyk] Upgrade @aws-sdk/types from 3.347.0 to 3.357.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2592 [Snyk] Upgrade @pulumi/pulumi from 3.72.2 to 3.73.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2584 [Snyk] Upgrade @docusaurus/core from 2.0.0-alpha.66 to 2.4.1
  docs/website/package.json
Labels: size/XS

#2599 Botonic version 0.23.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-google-analytics/package-lock.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package-lock.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-hubtype-babel/src/options.ts
  packages/botonic-plugin-inbenta/package-lock.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-luis/package-lock.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package-lock.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package-lock.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/M

#2596 [Snyk] Upgrade @oclif/command from 1.8.29 to 1.8.32
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2598 [Snyk] Upgrade contentful-import from 8.5.58 to 8.5.62
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2602 botonic-react: render images sent to the bot by user
  packages/botonic-react/src/components/image.jsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2603 botonic-react: add imagePreviewer in ThemeProps
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/util/environment.js
Labels: size/XS

#2607 docs(plugin-flow-builder): update github url in REDME and update docs
  docs/docs/plugins/plugin-flow-builder.md
  docs/package-lock.json
  packages/botonic-plugin-flow-builder/README.md
Labels: size/XS

#2609 0.23.0 packeges versions
  packages/botonic-cli/README.md
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-plugin-dialogflow/package-lock.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dialogflow/tests/index.test.ts
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-dynamodb/src/infrastructure/dynamo.ts
  packages/botonic-plugin-dynamodb/tests/domain/time.test.ts
  packages/botonic-plugin-dynamodb/tests/domain/track.test.ts
  packages/botonic-plugin-dynamodb/tests/infrastructure/dynamo.integration.test.ts
Labels: size/M
