Repository hubtype/botonic, pull requests merged in 2023-07, with the labels that each got.

#2537 Flow builder: tracking with Hubtype analytics events
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action.tsx
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/intent.ts
  packages/botonic-plugin-flow-builder/src/action/keyword.ts
  packages/botonic-plugin-flow-builder/src/action/tracking.ts
  packages/botonic-plugin-flow-builder/src/action/user-input.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/functions/index.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/L

#2547 [Snyk] Upgrade cross-fetch from 3.1.4 to 3.1.6
  packages/botonic-nlp/package-lock.json
  packages/botonic-nlp/package.json
Labels: size/XS

#2550 [Snyk] Upgrade @babel/runtime from 7.21.0 to 7.22.3
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2551 [Snyk] Upgrade @nlpjs/ner from 4.26.1 to 4.27.0
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2552 Trigger Button with notifications
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message.jsx
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/contexts.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/hooks.js
  packages/botonic-react/src/webchat/messages-reducer.js
  packages/botonic-react/src/webchat/trigger-button/index.tsx
  packages/botonic-react/src/webchat/trigger-button/styles.ts
  packages/botonic-react/src/webchat/webchat-reducer.js
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2535 chore(botonic): upgrade ts-node
  package-lock.json
  package.json
Labels: size/XS

#2553 Feat(flow-builder): allow having multiple buttons pointing to the same target #BLT-163
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-row.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-section.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
Labels: size/M

#2516 Whatsapp markdown #SER-2297
  packages/botonic-react/package-lock.json
  packages/botonic-react/src/components/multichannel/multichannel-carousel.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/multichannel.jsx
  packages/botonic-react/src/components/multichannel/whatsapp/markdown.ts
  packages/botonic-react/tsconfig.esm.json
  packages/botonic-react/tsconfig.json
Labels: size/L

#2555 [Snyk] Security upgrade @babel/plugin-transform-runtime from 7.15.8 to 7.22.6
  packages/botonic-api/package-lock.json
  packages/botonic-api/package.json
Labels: size/XS

#2556 [Snyk] Upgrade tslib from 2.5.0 to 2.5.3
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2558 [Snyk] Security upgrade @babel/plugin-transform-runtime from 7.15.8 to 7.22.0
  packages/botonic-api/package-lock.json
Labels: size/XS

#2557 [Snyk] Upgrade @oclif/command from 1.8.24 to 1.8.27
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2549 [Snyk] Upgrade contentful-import from 8.5.46 to 8.5.57
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2563 [Snyk] Upgrade semver from 7.5.0 to 7.5.2
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2564 [Snyk] Upgrade @aws-sdk/types from 3.342.0 to 3.347.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2562 [Snyk] Upgrade @pulumi/pulumi from 3.69.0 to 3.72.2
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2560 chore(botonic-react): publish version 0.22.6
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/XS

#2554 [Snyk] Security upgrade @docusaurus/preset-classic from 2.0.0-alpha.66 to 2.0.0
  docs/website/package.json
Labels: size/XS

#2565 [Snyk] Upgrade @babel/runtime from 7.22.3 to 7.22.5
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2561 [Snyk] Upgrade @aws-sdk/client-cloudfront from 3.345.0 to 3.354.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2566 [Snyk] Upgrade @oclif/config from 1.18.8 to 1.18.10
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2567 [Snyk] Upgrade @oclif/command from 1.8.27 to 1.8.28
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2568 [Snyk] Upgrade qs from 6.11.1 to 6.11.2
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2569 [Snyk] Upgrade @botonic/core from 0.21.6 to 0.22.0
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/XS

#2570 [Snyk] Upgrade @babel/runtime from 7.22.3 to 7.22.5
  packages/botonic-plugin-hubtype-babel/package-lock.json
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/XS

#2573 [Snyk] Upgrade @oclif/command from 1.8.28 to 1.8.29
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2572 [Snyk] Upgrade @botonic/core from 0.21.6 to 0.22.0
  packages/botonic-plugin-google-translation/package-lock.json
  packages/botonic-plugin-google-translation/package.json
Labels: size/XS

#2571 [Snyk] Upgrade @babel/runtime from 7.15.4 to 7.22.5
  packages/botonic-plugin-google-translation/package-lock.json
  packages/botonic-plugin-google-translation/package.json
Labels: size/XS

#2548 Botonic scripts: Translate bash scripts to Typescript #SER-2405
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  scripts/README.md
  scripts/ci/bump-version.ts
  scripts/ci/old/bump-version.sh
  scripts/ci/old/prepare-packages.sh
  scripts/ci/old/upgrade-deps.sh
  scripts/ci/prepare-packages.ts
  scripts/ci/upgrade-deps.ts
  scripts/package-lock.json
  scripts/package.json
  scripts/qa/cloc-all-packages.ts
  scripts/qa/cloc-package.ts
  scripts/qa/lint-all-packages.ts
  scripts/qa/lint-d-ts.ts
  scripts/qa/lint-package.ts
  scripts/qa/old/cloc-all-packages.sh
  scripts/qa/old/cloc-package.sh
  scripts/qa/old/lint-all-packages.sh
  scripts/qa/old/lint-d-ts.sh
  scripts/qa/old/lint-package.sh
Labels: size/L

#2578 [Snyk] Upgrade html-entities from 2.3.5 to 2.4.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2577 [Snyk] Upgrade aws-sdk from 2.1392.0 to 2.1404.0
  packages/botonic-core/package-lock.json
  packages/botonic-core/package.json
Labels: size/XS

#2576 [Snyk] Upgrade @babel/runtime from 7.15.4 to 7.22.5
  packages/botonic-plugin-dialogflow/package-lock.json
  packages/botonic-plugin-dialogflow/package.json
Labels: size/XS

#2575 [Snyk] Upgrade @botonic/core from 0.21.6 to 0.22.0
  packages/botonic-plugin-google-analytics/package-lock.json
  packages/botonic-plugin-google-analytics/package.json
Labels: size/XS

#2574 [Snyk] Upgrade contentful-import from 8.5.57 to 8.5.58
  packages/botonic-plugin-contentful/package-lock.json
  packages/botonic-plugin-contentful/package.json
Labels: size/XS

#2579 [Snyk] Upgrade aws-sdk from 2.1365.0 to 2.1404.0
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2580 [Snyk] Upgrade @babel/runtime from 7.14.8 to 7.22.5
  packages/botonic-plugin-dynamodb/package-lock.json
  packages/botonic-plugin-dynamodb/package.json
Labels: size/XS

#2581 [Snyk] Upgrade tslib from 2.5.3 to 2.6.0
  packages/botonic-cli/package-lock.json
  packages/botonic-cli/package.json
Labels: size/XS

#2582 [Snyk] Security upgrade @aws-sdk/client-cloudfront from 3.354.0 to 3.359.0
  packages/botonic-pulumi/package-lock.json
  packages/botonic-pulumi/package.json
Labels: size/XS

#2586 [Snyk] Upgrade @botonic/core from 0.21.5 to 0.22.0
  packages/botonic-plugin-dialogflow/package-lock.json
  packages/botonic-plugin-dialogflow/package.json
Labels: size/XS

#2587 [Snyk] Upgrade @babel/runtime from 7.16.5 to 7.22.5
  packages/botonic-plugin-dialogflow/package-lock.json
  packages/botonic-plugin-dialogflow/package.json
Labels: size/XS

#2585 [Snyk] Upgrade @docusaurus/preset-classic from 2.0.0 to 2.4.1
  docs/website/package.json
Labels: size/XS

#2589 Botonic react: property to disable trigger button notifications
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/index.ts
  packages/botonic-react/src/webchat/trigger-button/index.tsx
Labels: size/M

#2559 Flow Builder: Add a variable in a text from Flow Builder
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/M
