Repository hubtype/botonic, pull requests merged in 2024-09, with the labels that each got.

#2890 [Snyk] Upgrade zip-a-folder from 3.1.6 to 3.1.7
  packages/botonic-cli/package.json
Labels: size/XS

#2899 plugin-hubtype-analytics: HandoffOption evennt optional params
  package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-option.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
Labels: size/S

#2905 refactor: remove jwt code logic
  packages/botonic-react/src/webchat/actions.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/webchat-reducer.ts
Labels: size/S

#2906 chore: update ua-parser-js
  package-lock.json
  packages/botonic-react/package.json
Labels: size/XS

#2907 refactor: simplify webviews frame and remove react-frame-component
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/webview.jsx
Labels: size/M
