Repository hubtype/botonic, pull requests merged in 2024-03, with the labels that each got.

#2785 Create botonic-ci-test-all-packages.yml
  .github/workflows/botonic-ci-test-all-packages.yml
Labels: size/L

#2782 plugin-flow-builder: check if agents are available in conditional queue
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/function.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/M

#2786 botonic-react: in custom messages set for default sentBy to bot
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/custom-message.jsx
  packages/botonic-react/src/webchat/messages-reducer.ts
  packages/botonic-react/tests/components/__snapshots__/custom-message.test.jsx.snap
Labels: size/S

#2784 plugin-flow-builder: resolve the bot's locale by searching the flow's locale array
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/M

#2787 plugin-flow-builder: be able to use bot actions in whatsapp button list
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-row.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-section.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/S

#2789 plugin-flow-builder: use resolvedLocale in knowledge-base
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
Labels: size/S

#2788 plugin-flow-builder: country conditional function
  packages/botonic-plugin-flow-builder/src/functions/conditional-country.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts
  packages/botonic-plugin-flow-builder/src/functions/index.ts
Labels: size/S

#2791 plugin-flow-builder: add custom conditional
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-bot-variable.ts
  packages/botonic-plugin-flow-builder/src/functions/index.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
Labels: size/M

#2797 plugin-flow-builder: resolve regex in keywords
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
Labels: size/S

#2798 plugin-knowledge-bases: add is_faithful param in api response
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
Labels: size/XS

#2799 publish plugin-flow-builder and plugin-knowledge-bases
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-knowledge-bases/package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
Labels: size/M

#2801 botonic-react: truncate contents in WhatsappButtonList component if they exceed the limits
  CHANGELOG.md
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/multichannel/multichannel-button.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/whatsapp-button-list.tsx
  packages/botonic-react/src/util/index.ts
  packages/botonic-react/src/util/strings.ts
  packages/botonic-react/tests/components/__snapshots__/whatsapp-button-list.test.jsx.snap
  packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
  packages/botonic-react/tests/components/whatsapp-button-list.test.jsx
Labels: size/L

#2803 plugin-flow-builder: add support for smart intent nodes
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/smart-intent.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Labels: size/L

#2790 plugin-flow-builder: use only content id outside plugin
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/smart-intent.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Labels: size/L

#2807 release: botonic 0.25.0
  CHANGELOG.md
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/handoff/package.json
  examples/intent/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L
