Repository hubtype/botonic, pull requests merged in 2024-12, with the labels that each got.

#2942 botonic-react: ensure typing is visible by scrolling when typing is active #BLT-1243
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/actions.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/message-list/styles.ts
  packages/botonic-react/src/webchat/typing-indicator/index.tsx
  packages/botonic-react/src/webchat/typing-indicator/styles.ts
  packages/botonic-react/src/webchat/webchat-reducer.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2944 plugin-flow-builder: create executeConversationStart #BLT-1259
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
Labels: size/M

#2946 Add needs escalation as a webview end fail
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/types.ts
Labels: size/XS

#2951 chore: update blank-typescript example with rspack
  examples/blank-typescript/package.json
  examples/blank-typescript/rspack.config.js
  examples/blank-typescript/tsconfig.json
  examples/blank-typescript/webpack-entries/dev-entry.ts
  examples/blank-typescript/webpack-entries/node-entry.ts
  examples/blank-typescript/webpack-entries/webchat-entry.ts
  examples/blank-typescript/webpack-entries/webviews-entry.ts
  examples/blank-typescript/webpack.config.js
Labels: size/XL

#2948 chore: update github action dependency #PLA-2658
  .github/workflows/botonic-common-workflow.yml
  .github/workflows/botonic-docs-netlify-deploy.yml
  .github/workflows/botonic-docs-tests.yml
  docs/package-lock.json
  docs/package.json
Labels: size/XS
