Repository hubtype/botonic, pull requests merged in 2024-10, with the labels that each got.

#2908 botonic-react: type closeWebview as an async function
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webchat/webchat.jsx
  packages/botonic-react/src/webchat/webview.jsx
  packages/botonic-react/src/webview-app.tsx
Labels: size/M

#2910 botonic: prepare release v0.30.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/handoff/package.json
  examples/intent/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#2884 cli: send bot config to backend in botonic deploy #BLT-1008
  CHANGELOG.md
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/interfaces.ts
  packages/botonic-cli/src/util/bot-config.ts
  packages/botonic-cli/tests/commands/deploy.test.ts
Labels: size/XL

#2902 botonic-react: remove getConfig function #BLT-1036
  CHANGELOG.md
  packages/botonic-react/src/node-app.jsx
Labels: size/S

#2898 plugin-flow-builder: bot action as follow up, first node in a flow, after conditionals etc
  CHANGELOG.md
  package-lock.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-bot-action.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/bot-action.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
  packages/botonic-react/src/webchat/utils.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2909 plugin-flow-builder: when user clicks on old button send fallback #BLT-1070
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/tests/payload.test.ts
Labels: size/M

#2911 botonic-core: add attributes in input type for push notifications
  packages/botonic-core/src/models/legacy-types.ts
Labels: size/XS

#2912 plugin-flow-builder: store in session every new flow_thread_id
  packages/botonic-plugin-flow-builder/src/tracking.ts
Labels: size/XS

#2913 improve flowbuilder webview contents #BLT-1131
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
Labels: size/M

#2914 botonic-react: new typing indicator component
  packages/botonic-react/src/webchat/components/typing-indicator.jsx
  packages/botonic-react/src/webchat/components/typing-indicator.scss
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/typing-indicator/index.tsx
  packages/botonic-react/src/webchat/typing-indicator/styles.ts
Labels: size/L

#2900 refactor: get rid of Simplebar (vanilla js based scrollbar)
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/carousel.jsx
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/util/dom.js
  packages/botonic-react/src/webchat/components/styled-scrollbar.jsx
  packages/botonic-react/src/webchat/components/styled-scrollbar.scss
  packages/botonic-react/src/webchat/constants.ts
  packages/botonic-react/src/webchat/devices/device-adapter.js
  packages/botonic-react/src/webchat/devices/scrollbar-controller.js
  packages/botonic-react/src/webchat/devices/webchat-resizer.js
  packages/botonic-react/src/webchat/header.jsx
  packages/botonic-react/src/webchat/hooks/index.ts
  packages/botonic-react/src/webchat/hooks/use-device-adapter.ts
  packages/botonic-react/src/webchat/hooks/use-scroll-to-bottom.ts
  packages/botonic-react/src/webchat/hooks/use-scrollbar-controller.ts
  packages/botonic-react/src/webchat/hooks/use-virtual-keyboard-detection.ts
  packages/botonic-react/src/webchat/hooks/use-webchat-dimensions.ts
  packages/botonic-react/src/webchat/hooks/use-webchat-resizer.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/message-list/scroll-button.tsx
  packages/botonic-react/src/webchat/message-list/styles.ts
  packages/botonic-react/src/webchat/replies.jsx
  packages/botonic-react/src/webchat/webchat-chat-area/index.tsx
  packages/botonic-react/src/webchat/webchat-chat-area/styles.ts
  packages/botonic-react/src/webchat/webchat-input-panel/index.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/textarea.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/XXL

#2915 Smart intents in local
  packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Labels: size/XS

#2918 fix: fix scroll to bottom via querySelector instead of ref
  packages/botonic-react/src/util/dom.js
  packages/botonic-react/src/webchat/hooks/use-scroll-to-bottom.ts
Labels: size/S

#2919 Botonic cli regex bot config
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/util/bot-config.ts
Labels: size/S

#2921 publish 0.30.1 for core and react
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-react/package.json
Labels: size/XS

#2916 refactor: remove webchat prefix from input panel and chat area
  package-lock.json
  packages/botonic-react/src/webchat/chat-area/index.tsx
  packages/botonic-react/src/webchat/chat-area/styles.ts
  packages/botonic-react/src/webchat/input-panel/attachment.tsx
  packages/botonic-react/src/webchat/input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/input-panel/index.tsx
  packages/botonic-react/src/webchat/input-panel/opened-emoji-picker.tsx
  packages/botonic-react/src/webchat/input-panel/persistent-menu.tsx
  packages/botonic-react/src/webchat/input-panel/send-button.tsx
  packages/botonic-react/src/webchat/input-panel/styles.ts
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2924 refactor(botonic-react): add padding to fix height
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/input-panel/styles.ts
Labels: size/XS

#2923 plugin-hubtype-analytics: add an enum for webviewEndFailType
  package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
Labels: size/S

#2927 fix: take into account header and input when recalculating webchat di…
  packages/botonic-react/src/webchat/hooks/use-webchat-dimensions.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/S

#2926 tech-feat: botonic packages to use uuid v7
  package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-cli/src/analytics/credentials-handler.ts
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dialogflow/src/index.ts
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-react/jest.config.js
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-feedback.tsx
  packages/botonic-react/src/util/webchat.js
  packages/botonic-react/src/webchat/input-panel/index.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/M

#2925 cli: fix error fetching more bots
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/interfaces.ts
Labels: size/M
