Repository hubtype/botonic, pull requests merged in 2024-05, with the labels that each got.

#2814 botonic-react: options can be undefined
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/webchat.jsx
  packages/botonic-react/src/webview-app.tsx
Labels: size/S

#2815 plugin-flow-builder: avoid to call smart intents api
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Labels: size/XS

#2812 chore(core): Remove unused code from experimental 1.0 version
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/data-provider/dynamodb-data-provider.ts
  packages/botonic-core/src/data-provider/dynamodb-utils.ts
  packages/botonic-core/src/data-provider/factory.ts
  packages/botonic-core/src/data-provider/index.ts
  packages/botonic-core/src/data-provider/local-data-provider.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/index.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/output-parser/botonic-output-parser.ts
  packages/botonic-core/src/output-parser/factory.ts
  packages/botonic-core/src/output-parser/index.ts
  packages/botonic-core/src/output-parser/parsers.ts
  packages/botonic-core/src/plugins.ts
  packages/botonic-core/src/utils.ts
  packages/botonic-core/tests/helpers/parsing.ts
  packages/botonic-core/tests/helpers/routing.ts
  packages/botonic-core/tests/parsing/carousel.test.tsx
  packages/botonic-core/tests/parsing/contact.test.tsx
  packages/botonic-core/tests/parsing/custom.test.tsx
  packages/botonic-core/tests/parsing/form.test.tsx
  packages/botonic-core/tests/parsing/location.test.tsx
  packages/botonic-core/tests/parsing/media.test.tsx
  packages/botonic-core/tests/parsing/text.test.tsx
  packages/botonic-core/tests/parsing/user-events.test.tsx
  packages/botonic-dx/baseline/jest.config.js
  packages/botonic-dx/package.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/multichannel/multichannel-button.jsx
  packages/botonic-react/src/components/multichannel/multichannel-carousel.jsx
  packages/botonic-react/src/components/multichannel/multichannel-reply.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/multichannel-utils.js
  packages/botonic-react/src/components/multichannel/multichannel.jsx
Labels: size/XXL

#2817 plugin-flow-builder: bot action limit characters
  .github/workflows/botonic-plugin-flow-builder-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/babel.config.js
  packages/botonic-plugin-flow-builder/jest.config.js
  packages/botonic-plugin-flow-builder/jest.setup.js
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/button.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tsconfig.tests.json
Labels: size/XL

#2816 Botonic-React: add url icon theme property
  packages/botonic-react/package-lock.json
  packages/botonic-react/src/assets/url-icon.png
  packages/botonic-react/src/components/button.jsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/constants.js
Labels: size/M

#2821 plugin-flow-builder: handoff test
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/conditional-queue.ts
  packages/botonic-plugin-flow-builder/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
Labels: size/L

#2823 plugin-flow-builder: test conditional nodes
  packages/botonic-plugin-flow-builder/tests/conditional-bot-variable.test.ts
  packages/botonic-plugin-flow-builder/tests/conditional-channel.test.ts
  packages/botonic-plugin-flow-builder/tests/conditional-country.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
Labels: size/XXL

#2824 plugin-flow-builder: test different types of messages
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-button-list.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-carousel.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-image.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-text.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-url-button.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-video.test.ts
Labels: size/L

#2825 feat/flow-builder-plugin-smart-intents-v2
  CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
Labels: size/M

#2826 botonic-react: Fix webviews not closing on fb #PLA-2162
  packages/botonic-react/src/webview-app.tsx
Labels: size/S

#2832 plugin-hubtype-analytics: update fallabck event
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
Labels: size/L

#2830 plugin-hubtype-analytics: ai events
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-ai-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-keyword-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-classic.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-classic.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
Labels: size/XL

#2829 plugin-hubtype-analytics: handoff events
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-ai-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-keyword-model.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-fail.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-success.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-classic.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-classic.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
Labels: size/XL

#2818 Botonic version 0.26.x-alpha before 0.27.0
  CHANGELOG.md
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-dx/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-react/package.json
Labels: size/M

#2840 plugin-flow-builder: knowledge base events
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
Labels: size/L

#2839 plugin-knowledge-bases: new inference endpoint without knowledge base id
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/L

#2838 plugin-hubtype-analytics: create custom events
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/L

#2837 plugin-hubtype-analytics: webview events as webevent
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/XL

#2836 plugin-hubtype-analytics: renames and fix types
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/XL

#2835 core & plugin-flow-builder: HandoffBuilder withBotEvent
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/XL

#2834 plugin-flow-builder: use new events fallback keyword intent smart intent
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/XXL

#2845 chore: publish 0.27.0-alpha.1
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tsconfig.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package.json
Labels: size/L

#2844 plugin-hubtype-analytics: enums with PascalCase
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tsconfig.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package.json
Labels: size/L

#2843 refactor(plugin-hubtype-analytics): remove channel and created_at fro…
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tsconfig.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package.json
Labels: size/L

#2842 plugin-hubtype-analytics: refactor custom event
  .github/workflows/botonic-plugin-flow-builder-tests.yml
  .github/workflows/botonic-plugin-hubtype-analytics-tests.yml
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tsconfig.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package.json
Labels: size/XL
