Repository hubtype/botonic, pull requests merged in 2024-11, with the labels that each got.

#2928 chore: bump packages using uuid v7
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/package.json
Labels: size/S

#2932 botonic-core: export interface HubtypeHandoffParams
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
Labels: size/XS

#2930 botonic-react: messenger markdown not applied #BLT-1152
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/whatsapp/markdown.ts
Labels: size/S

#2931 botonic-react: fix mixed markdowns used in the same text #BLT-1177
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/whatsapp/markdown-meta.ts
  packages/botonic-react/src/components/multichannel/whatsapp/markdown.ts
  packages/botonic-react/src/components/whatsapp-button-list.tsx
  packages/botonic-react/src/components/whatsapp-cta-url-button.tsx
  packages/botonic-react/tests/components/multichannel/markdown.test.js
Labels: size/L

#2933 botonic-react: remove unused scrollbar props
  packages/botonic-react/src/components/index-types.ts
Labels: size/S

#2935 Publish 0.30.4
  CHANGELOG.md
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/package.json
Labels: size/S

#2936 botonic-react: pass Button code to typescript
  packages/botonic-react/src/components/button.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
Labels: size/M

#2938 botonic-react: fix cover component in botonic react #BLT-1223
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/cover-component/index.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2940 plugin-flow-builder: not show log when check if payload is from bot action node
  package-lock.json
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/M

#2941 chore(plugin-flow-builder): publish 0.30.6
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
Labels: size/XS

#2934 dx-bundler-rspack: create a dx package to build with rspack #BLT-1197
  package-lock.json
  packages/botonic-dx-bundler-rspack/.gitignore
  packages/botonic-dx-bundler-rspack/README.md
  packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-rspack/tsconfig.json
Labels: size/L

#2943 Remove strings that refer components #BLT-1258
  package-lock.json
  packages/botonic-dx-bundler-rspack/README.md
  packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts
  packages/botonic-react/package.json
  packages/botonic-react/src/components/element.jsx
  packages/botonic-react/src/components/multichannel/multichannel-button.jsx
  packages/botonic-react/src/components/multichannel/multichannel-carousel.jsx
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
  packages/botonic-react/src/components/multichannel/multichannel-utils.js
  packages/botonic-react/src/components/multichannel/multichannel.jsx
  packages/botonic-react/src/components/multichannel/whatsapp/constants.ts
  packages/botonic-react/src/components/whatsapp-button-list.tsx
  packages/botonic-react/src/components/whatsapp-cta-url-button.tsx
  packages/botonic-react/src/constants.js
Labels: size/L
