Repository hubtype/botonic, pull requests merged in 2024-07, with the labels that each got.

#2853 plugin-flow-builder: resolve keywords, smart intents and intents in first interaction
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/knowledge-base.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/knowledge-base.ts
  packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
Labels: size/XL

#2864 plugin-flow-builder: avoid send webchatsettings when channel in't webchat
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
Labels: size/S

#2863 plugin-flow-builder: create contents with map
  package-lock.json
  packages/botonic-plugin-flow-builder/README.md
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/webview/contents-context.ts
  packages/botonic-plugin-flow-builder/src/webview/index.ts
  packages/botonic-plugin-flow-builder/src/webview/types.ts
  packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
Labels: size/L

#2855 Feat/handle preview for is_test_integration apps
  CHANGELOG.md
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-core/tests/helpers/core-bot.ts
  packages/botonic-core/tests/helpers/routing.ts
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
Labels: size/L

#2866 plugin-hubtype-analytics: update README
  packages/botonic-plugin-hubtype-analytics/README.md
Labels: size/L

#2867 Release 0.28.0
  CHANGELOG.md
  package-lock.json
  packages/botonic-cli/package.json
  packages/botonic-core/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/L

#2868 Fix bot action after handoff in test integration preview
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/handoff.ts
Labels: size/L

#2869 Fix events in test integration
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
Labels: size/S

#2870 botonic-react: remove framer motion
  packages/botonic-core/src/core-bot.ts
  packages/botonic-react/package.json
  packages/botonic-react/src/shared/styles.ts
  packages/botonic-react/src/webchat/components/conditional-animation.jsx
  packages/botonic-react/src/webchat/header.jsx
Labels: size/M

#2872 botonic-react: remove unescape, qrcode.react and he dependencies
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/botonic-tester.jsx
Labels: size/M

#2871 plugin-flow-builder: check track events with tests
  packages/botonic-plugin-flow-builder/README.md
  packages/botonic-plugin-flow-builder/tests/__mocks__/index.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/track-event.ts
  packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
  packages/botonic-plugin-flow-builder/tests/conditional-bot-variable.test.ts
  packages/botonic-plugin-flow-builder/tests/conditional-channel.test.ts
  packages/botonic-plugin-flow-builder/tests/conditional-country.test.ts
  packages/botonic-plugin-flow-builder/tests/fallback.test.ts
  packages/botonic-plugin-flow-builder/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-button-list.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-carousel.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-image.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-text.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-url-button.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-video.test.ts
  packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-fallback.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-smart-intent.test.ts
Labels: size/XL

#2877 plugin-hubtype-analytics: Add target bot_interaction_id on feedback knowledge base events
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/routing/router.match-route.test.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-knowledge-base.tsx
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback-knowledgebase.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview-end.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview-step.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/src/utils.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback-knowledgebase.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-feedback.tsx
  packages/botonic-react/src/components/message/message-footer.tsx
  packages/botonic-react/src/components/text.tsx
Labels: size/L

#2878 Blt 992 plugin hubtype analytics create new web event endpoint
  package-lock.json
  package.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-plugin-flow-builder/package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback-knowledgebase.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview-step.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback-knowledgebase.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-feedback.tsx
Labels: size/L
