Repository hubtype/botonic, pull requests merged in 2024-08, with the labels that each got.

#2880 plugin-knowledge-bases: update api endpoint to use source ids #BLT-983
  CHANGELOG.md
  package-lock.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/M

#2888 Release/0.29.0
  CHANGELOG.md
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/M

#2886 botonic-react: components for WebchatInputPanel
  packages/botonic-react/src/webchat/components/opened-persistent-menu.jsx
  packages/botonic-react/src/webchat/textarea/styles.ts
  packages/botonic-react/src/webchat/webchat-input-panel/attachment.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/index.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/opened-emoji-picker.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/persistent-menu.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/send-button.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/styles.ts
  packages/botonic-react/src/webchat/webchat-input-panel/textarea.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2879 botonic-react: remove use-async-effect dependency
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/XS

#2893 plugin-dialogflow: fix tests
  packages/botonic-plugin-dialogflow/tests/index.test.ts
Labels: size/XS

#2895 botonic-cli: no read/write bot.config.json
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/commands/deploy.ts
  packages/botonic-cli/src/util/bot-config.ts
  packages/botonic-cli/tests/commands/deploy.test.ts
Labels: size/M

#2882 botonic-react: upgrade react-textarea-autosize
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webchat/components/opened-persistent-menu.jsx
  packages/botonic-react/src/webchat/webchat-input-panel/attachment.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/index.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/opened-emoji-picker.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/persistent-menu.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/send-button.tsx
  packages/botonic-react/src/webchat/webchat-input-panel/styles.ts
  packages/botonic-react/src/webchat/webchat-input-panel/textarea.tsx
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/XL

#2896 botonic-react: position fixed in UnreadMessagesCounter
  packages/botonic-react/src/webchat/trigger-button/styles.ts
Labels: size/XS
