Repository hubtype/botonic, pull requests merged in 2024-06, with the labels that each got.

#2846 Analytics v2: Refactor events by removing data field
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-option.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
Labels: size/XL

#2848 plugin-hubtype-analytics: add user input in nlu events
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
Labels: size/S

#2852 fix(plugin-flow-builder): add is meaningful node tracking #874
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
Labels: size/XS

#2851 fix: update Custom, Fallback and FlowNode (is_meaningful) events with missing fields and use them #BLT-888
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/fallback.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
Labels: size/M

#2856 plugin-flow-builder: fix uuid for flowThreadId
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/tracking.ts
Labels: size/XS

#2850 botonic-react: add params in WhatsappCTAURLButton when use it inside Multichannel
  packages/botonic-react/src/components/multichannel/multichannel-text.jsx
Labels: size/XS

#2858 plugin-flow-builder: add await when call trackEvent function
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/fallback.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Labels: size/XS

#2854 Botonic - React: scroll to bottom when typing
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/shared/styles.ts
  packages/botonic-react/src/webchat/devices/device-adapter.js
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/message-list/intro-message.tsx
  packages/botonic-react/src/webchat/message-list/scroll-button.tsx
  packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx
  packages/botonic-react/src/webchat/message-list/use-notifications.ts
  packages/botonic-react/src/webchat/webchat.jsx
Labels: size/L

#2861 Botonic-React: change staticAsset function + add unit tests
  package-lock.json
  packages/botonic-react/package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/util/environment.js
  packages/botonic-react/tests/utils.test.js
Labels: size/L

#2862 plugin-flow-builder: publish 0.27.6
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
Labels: size/XS

#2857 botonic-dx: update eslint rules
  package-lock.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/index.js
  packages/botonic-eslint-config/package.json
Labels: size/XS
