Repository hubtype/botonic, pull requests merged in 2025-03, with the labels that each got.

#2987 feat(btonic-plugin-flow-builder): Use the queue's availability endpoint from External API #PLA-2771
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
Labels: size/XS

#2985 feat(core/plugin-flow-builder): add support for notifying queue position changed #BLT-1449
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/handoff.ts
  packages/botonic-react/package.json
  packages/botonic-react/src/index-types.ts
Labels: size/M

#2988 Release/0.33.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/package.json
  examples/flow-builder-typescript/src/server/config.ts
  examples/flow-builder-typescript/src/server/utils/env-utils.ts
  examples/handoff/package.json
  examples/intent/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/CHANGELOG.md
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#2990 feat: remove files from package.json
  examples/flow-builder-typescript/package.json
Labels: size/XS

#2997 refactor(core): add interfaces for input event
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
Labels: size/M
