Repository hubtype/botonic, pull requests merged in 2025-06, with the labels that each got.

#3029 plugin-flow-builder: add contentFilters #BLT-1683
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/filters/index.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/tests/ai-agent.test.ts
  packages/botonic-plugin-flow-builder/tests/content-filters/remove-button.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
Labels: size/L

#3031 feat: retrieve context for webviews from new external api endpoint for bot session context
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/webview-app.tsx
Labels: size/M

#3036 plugin flow-builder & ai-agents: rename tools to active_tools in flow ai-agent node
  package-lock.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/index.ts
  packages/botonic-plugin-ai-agents/src/types.ts
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/ai-agent.ts
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/ai-agent.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/S

#3040 botonic: remove diferents plugins to create intents
  .github/workflows/botonic-ci-test-all-packages.yml
  .github/workflows/botonic-plugin-dialogflow-tests.yml
  .github/workflows/botonic-plugin-inbenta-tests.yml
  .github/workflows/botonic-plugin-luis-tests.yml
  .github/workflows/botonic-plugin-watson-tests.yml
  packages/botonic-plugin-dialogflow/CHANGELOG.md
  packages/botonic-plugin-dialogflow/README.md
  packages/botonic-plugin-dialogflow/jest.config.js
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dialogflow/src/index.ts
  packages/botonic-plugin-dialogflow/src/types.ts
  packages/botonic-plugin-dialogflow/tests/index.test.ts
  packages/botonic-plugin-dialogflow/tsconfig.esm.json
  packages/botonic-plugin-dialogflow/tsconfig.json
  packages/botonic-plugin-hubtype-babel/CHANGELOG.md
  packages/botonic-plugin-hubtype-babel/README.md
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
  packages/botonic-plugin-hubtype-babel/src/index.ts
  packages/botonic-plugin-hubtype-babel/src/options.ts
  packages/botonic-plugin-hubtype-babel/tsconfig.esm.json
  packages/botonic-plugin-hubtype-babel/tsconfig.json
  packages/botonic-plugin-inbenta/CHANGELOG.md
  packages/botonic-plugin-inbenta/README.md
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-inbenta/src/index.js
  packages/botonic-plugin-luis/CHANGELOG.md
  packages/botonic-plugin-luis/README.md
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-luis/src/index.js
  packages/botonic-plugin-watson/CHANGELOG.md
  packages/botonic-plugin-watson/README.md
  packages/botonic-plugin-watson/package.json
  packages/botonic-plugin-watson/src/index.js
  packages/botonic-plugin-watson/src/watson-output-parser.js
  scripts/nlu/README.md
  scripts/nlu/best-model-search.ts
  scripts/nlu/csv-generator.ts
  scripts/nlu/dump_word_embedding_to_db.js
  scripts/nlu/load-model.ts
  scripts/nlu/parse-new-dataset.js
  scripts/nlu/train-model.ts
  scripts/nlu/txt-to-csv.ts
Labels: size/XXL

#3041 fix: botonic-publish action
  .github/workflows/botonic-publish.yml
Labels: size/XS

#3039 Botonic prepare to publish v0.36.0
  package-lock.json
  package.json
  packages/botonic-cli/package.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
Labels: size/L

#3042 botonic: bump core, google-translation, segment
  .github/workflows/botonic-publish.yml
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-segment/package.json
Labels: size/M

#3048 feat: fix webview events with user.locale and user.system_locale
  package-lock.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-react/package.json
  packages/botonic-react/src/webview-app.tsx
Labels: size/XS

#3050 react: Detect automatically if the webchat is running in iOS/Android webview
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/components/button/index.tsx
  packages/botonic-react/src/components/markdown.js
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/util/environment.js
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/tests/components/render-markdown.test.jsx
Labels: size/M

#3051 fix: fix carousel arrows position
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/components/carousel.tsx
Labels: size/S

#3052 plugin-ai-agents: add memory in local development
  package-lock.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/hubtype-client.ts
  packages/botonic-plugin-ai-agents/src/index.ts
Labels: size/M
