Repository hubtype/botonic, pull requests merged in 2025-04, with the labels that each got.

#2998 feat(core & plugin-flow-builder): add nluResult in input
  package-lock.json
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
Labels: size/L

#2992 botonic-react & plugin-flow-builder: allow creating test cases #BLT-1491
  package-lock.json
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-react/package.json
Labels: size/L

#3000 chore: bump all botonic versions to 0.34.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/package.json
  examples/handoff/package.json
  examples/intent/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-cli/tests/botonic-api-service.test.ts
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#3001 feat(plugin-flow-builder): allow shadowing configuration BLT-1539
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/intent.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
  packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
Labels: size/L

#3002 feat: WebviewRequestContext wrapp all WebviewContainer
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/webview/index.tsx
Labels: size/M

#3004 plugin-flow-builder: nluResolution available in first interaction
  package-lock.json
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
  packages/botonic-plugin-flow-builder/tests/keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
Labels: size/L

#3003 botonic-react: ReactBot class with typescript
  package-lock.json
  package.json
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/plugins.ts
  packages/botonic-core/src/routing/router-utils.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/react-bot.jsx
  packages/botonic-react/src/react-bot.tsx
Labels: size/L

#2991 botonic-react: refactor webchat theme and create default theme #BLT-1472
  packages/botonic-react/src/components/buttons-disabler.js
  packages/botonic-react/src/components/carousel.tsx
  packages/botonic-react/src/components/image.tsx
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-image.tsx
  packages/botonic-react/src/components/message/timestamps.tsx
  packages/botonic-react/src/components/reply.tsx
  packages/botonic-react/src/components/webchat-settings.tsx
  packages/botonic-react/src/constants.js
  packages/botonic-react/src/dev-app.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webchat-app.tsx
  packages/botonic-react/src/webchat/components/conditional-animation.jsx
  packages/botonic-react/src/webchat/components/opened-persistent-menu.jsx
  packages/botonic-react/src/webchat/context/index.tsx
  packages/botonic-react/src/webchat/context/types.ts
  packages/botonic-react/src/webchat/context/use-webchat.ts
  packages/botonic-react/src/webchat/header/default-header.tsx
  packages/botonic-react/src/webchat/header/styles.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/input-panel/attachment.tsx
  packages/botonic-react/src/webchat/input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/input-panel/index.tsx
  packages/botonic-react/src/webchat/input-panel/persistent-menu.tsx
  packages/botonic-react/src/webchat/input-panel/send-button.tsx
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
  packages/botonic-react/src/webchat/message-list/intro-message.tsx
  packages/botonic-react/src/webchat/message-list/use-notifications.ts
  packages/botonic-react/src/webchat/styles.ts
  packages/botonic-react/src/webchat/theme/default-theme.ts
  packages/botonic-react/src/webchat/theme/theme.d.ts
  packages/botonic-react/src/webchat/theme/types.ts
  packages/botonic-react/src/webchat/trigger-button/index.tsx
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/src/webchat/webview/index.tsx
  packages/botonic-react/src/webchat/webview/styles.ts
  packages/botonic-react/tests/webchat/webchat.component.test.jsx
Labels: size/XL

#2995 Refactor theme button style
  packages/botonic-react/src/components/button/index.tsx
  packages/botonic-react/src/components/button/styles.ts
  packages/botonic-react/src/components/buttons-disabler.js
  packages/botonic-react/src/webchat/theme/default-theme.ts
  packages/botonic-react/src/webchat/theme/types.ts
Labels: size/L

#3005 botonic-react: add user locale and user country on init webchat #BLT-1562
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/routing/router-utils.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/helpers/core-bot.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-react/src/components/webchat-settings.tsx
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/dev-app.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/time-zone-to-country-code.ts
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webchat-app.tsx
  packages/botonic-react/src/webchat/context/types.ts
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/src/webview-app.tsx
Labels: size/XL

#3009 fix: adapt actions to not use legacy cache
  .github/workflows/botonic-common-workflow.yml
  .github/workflows/botonic-docs-netlify-deploy.yml
  .github/workflows/botonic-docs-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit.yml
Labels: size/L

#3006 botonic-core: infer type of plugins to bot context #BLT-1574
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/src/plugins.ts
  packages/botonic-plugin-flow-builder/src/helpers.ts
Labels: size/M

#3007 botonic-core & botonic-react: BotContext with getUserLocale, geUserCountry and getSystemLocale functions
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/i18n.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/helpers/core-bot.ts
  packages/botonic-core/tests/helpers/routing.ts
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webview-app.tsx
Labels: size/L

#3008 plugin-flow-builder: use new user fields and default_locale_code #BLT-1581
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/src/utils.ts
  packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
Labels: size/L

#3010 feat(plugin-flow-builder): remove all logic related with intents babel #BLT-3010
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/intent.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/index.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
Labels: size/L

#3012 core & plugin-flow-builder: allow infer type of user.extra_data #BLT-1592
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/M

#3011 core & react & plugin-flow-builder: remove get string function from request bot context #BLT-1591
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/src/core-bot.ts
  packages/botonic-core/src/i18n.ts
  packages/botonic-core/src/index.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/core-bot/core-bot.test.ts
  packages/botonic-core/tests/helpers/core-bot.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/webview-app.tsx
  packages/botonic-react/tests/helpers/render-webchat-with-providers.jsx
Labels: size/M

#3013 plugin-flow-builder: no need to receive the locale in any function #BLT-1593
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/fallback.ts
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/functions/conditional-country.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/tests/conditional-country.test.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webchat/webchat.tsx
Labels: size/L
