Repository hubtype/botonic, pull requests merged in 2025-05, with the labels that each got.

#3014 Some fixes before 0.35.0
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-google-translation/src/index.ts
  packages/botonic-plugin-hubtype-analytics/src/index.ts
  packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-react/src/components/message/message-feedback.tsx
  packages/botonic-react/src/webchat/tracking.ts
Labels: size/L

#3016 feat(botonic-core): change _hubtype_case_status for _hubtype_case_resolution
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/src/models/legacy-types.ts
Labels: size/XS

#3017 feat(botonic-cli): Use v3 of users' endpoints and sign-up specific endpoint, and simplify the Me type
  packages/botonic-cli/src/botonic-api-service.ts
  packages/botonic-cli/src/interfaces.ts
Labels: size/S

#3015 @botonic publish version 0.35.0
  examples/blank-typescript/package.json
  examples/blank-typescript/src/plugins.ts
  examples/blank/package.json
  examples/blank/src/plugins.js
  examples/booking-platform/package.json
  examples/booking-platform/src/plugins.js
  examples/childs/package.json
  examples/childs/src/plugins.js
  examples/custom-webchat/package.json
  examples/custom-webchat/src/plugins.js
  examples/dynamic-carousel/package.json
  examples/dynamic-carousel/src/plugins.js
  examples/dynamodb/package.json
  examples/dynamodb/src/plugins.js
  examples/flow-builder-typescript/package.json
  examples/flow-builder-typescript/src/server/config.ts
  examples/flow-builder-typescript/src/server/domain/user-data.ts
  examples/flow-builder-typescript/src/server/plugins.ts
  examples/flow-builder-typescript/src/server/types.ts
  examples/handoff/package.json
  examples/handoff/src/plugins.js
  examples/intent/package.json
  examples/intent/src/plugins.js
  examples/telco-offers/package.json
  examples/telco-offers/src/plugins.js
  examples/tutorial/package.json
  examples/tutorial/src/plugins.js
  package-lock.json
  package.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-environment.ts
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#3018 feat(plugin-flow-builder): always adds match contents with some nlu
  package-lock.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/tests/execute-start-conversation.test.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-smart-intent.test.ts
Labels: size/L

#3020 chore: create gh action deploy botonic #PLA-2878
  .github/workflows/botonic-publish.yml
  package-lock.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-inbenta/package.json
  scripts/ci/botonic-publish.sh
Labels: size/XL

#3021 plugin-ai-agent: create new plugin-ai-agent #BLT-1633
  package-lock.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/ai-agent-client.ts
  packages/botonic-plugin-ai-agents/src/constants.ts
  packages/botonic-plugin-ai-agents/src/errors.ts
  packages/botonic-plugin-ai-agents/src/index.ts
  packages/botonic-plugin-ai-agents/src/types.ts
  packages/botonic-plugin-ai-agents/tsconfig.esm.json
  packages/botonic-plugin-ai-agents/tsconfig.json
Labels: size/L

#3026 Use bot context in routes and matcher
  package-lock.json
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
Labels: size/M
