Repository hubtype/botonic, pull requests merged in 2025-01, with the labels that each got.

#2953 feat(botonic-react): Replace scroll behavior in scrollIntoView for a CSS property
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/hooks/use-scroll-to-bottom.ts
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/message-list/styles.ts
Labels: size/S

#2939 botonic-react: upgrade react version to 18 #BLT-1231 #BLT-1232
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/dev-app.jsx
  packages/botonic-react/src/webchat-app.jsx
  packages/botonic-react/src/webchat/session-view.jsx
  packages/botonic-react/src/webview-app.tsx
  packages/botonic-react/tests/helpers/test-utils.jsx
  packages/botonic-react/tests/webchat/usewebchat.test.jsx
  packages/botonic-react/tests/webchat/webchat-app.test.jsx
Labels: size/L

#2947 botonic-react: Webchat component with typescript
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/index.ts
  packages/botonic-react/src/msg-to-botonic.jsx
  packages/botonic-react/src/webchat-app.tsx
  packages/botonic-react/src/webchat/actions.ts
  packages/botonic-react/src/webchat/global.d.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/styles.ts
  packages/botonic-react/src/webchat/webchat-reducer.ts
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/tests/webchat/storage.test.jsx
Labels: size/XL

#2949 botonic-react: Header component with typescript
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/src/webchat/header.jsx
  packages/botonic-react/src/webchat/header/default-header.tsx
  packages/botonic-react/src/webchat/header/index.tsx
  packages/botonic-react/src/webchat/header/styles.ts
Labels: size/L

#2950 botonic-react: some little changes using typescript
  package-lock.json
  package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/components/button.tsx
  packages/botonic-react/src/components/custom-message.tsx
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webchat/hooks/use-previous.ts
  packages/botonic-react/src/webchat/hooks/use-scrollbar-controller.ts
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/input-panel/attachment.tsx
  packages/botonic-react/src/webchat/input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/input-panel/index.tsx
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
Labels: size/L

#2952 botonic-react: WebchatReplies and Reply with typescript
  package-lock.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/src/components/reply.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat-app.tsx
  packages/botonic-react/src/webchat/actions.ts
  packages/botonic-react/src/webchat/chat-area/index.tsx
  packages/botonic-react/src/webchat/hooks/use-webchat.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/messages-reducer.ts
  packages/botonic-react/src/webchat/replies.jsx
  packages/botonic-react/src/webchat/replies/index.tsx
  packages/botonic-react/src/webchat/replies/styles.ts
  packages/botonic-react/src/webchat/webchat.tsx
Labels: size/L

#2964 botonic-react: Document component with typescript
  packages/botonic-react/src/components/document.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/msg-to-botonic.jsx
Labels: size/S

#2963 botonic-react: Audio component with typescript
  packages/botonic-react/src/components/audio.tsx
  packages/botonic-react/src/components/document.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/msg-to-botonic.jsx
Labels: size/M

#2962 botonic-react: Video component with typescript
  packages/botonic-react/src/components/audio.tsx
  packages/botonic-react/src/components/document.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/video.tsx
  packages/botonic-react/src/msg-to-botonic.jsx
Labels: size/M

#2961 botonic-react: Image component with typescript
  packages/botonic-react/src/components/audio.tsx
  packages/botonic-react/src/components/document.tsx
  packages/botonic-react/src/components/image.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/video.tsx
  packages/botonic-react/src/msg-to-botonic.jsx
  packages/botonic-react/src/webchat/webchat.tsx
Labels: size/M

#2966 botonic-react: create webchat context folder
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/button.tsx
  packages/botonic-react/src/components/carousel.jsx
  packages/botonic-react/src/components/document.tsx
  packages/botonic-react/src/components/handoff.jsx
  packages/botonic-react/src/components/image.tsx
  packages/botonic-react/src/components/message/index.jsx
  packages/botonic-react/src/components/message/message-feedback.tsx
  packages/botonic-react/src/components/message/message-footer.tsx
  packages/botonic-react/src/components/message/message-image.tsx
  packages/botonic-react/src/components/message/timestamps.tsx
  packages/botonic-react/src/components/reply.tsx
  packages/botonic-react/src/components/webchat-settings.tsx
  packages/botonic-react/src/contexts.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/index.ts
  packages/botonic-react/src/webchat/chat-area/index.tsx
  packages/botonic-react/src/webchat/components/conditional-animation.jsx
  packages/botonic-react/src/webchat/components/opened-persistent-menu.jsx
  packages/botonic-react/src/webchat/context/actions.ts
  packages/botonic-react/src/webchat/context/index.tsx
  packages/botonic-react/src/webchat/context/messages-reducer.ts
  packages/botonic-react/src/webchat/context/types.ts
  packages/botonic-react/src/webchat/context/use-webchat.ts
  packages/botonic-react/src/webchat/context/webchat-reducer.ts
  packages/botonic-react/src/webchat/cover-component/index.tsx
  packages/botonic-react/src/webchat/header/default-header.tsx
  packages/botonic-react/src/webchat/header/index.tsx
  packages/botonic-react/src/webchat/hooks/index.ts
  packages/botonic-react/src/webchat/hooks/use-scrollbar-controller.ts
  packages/botonic-react/src/webchat/hooks/use-typing.ts
  packages/botonic-react/src/webchat/hooks/use-webchat-dimensions.ts
  packages/botonic-react/src/webchat/hooks/use-webchat-resizer.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/index.ts
  packages/botonic-react/src/webchat/input-panel/attachment.tsx
  packages/botonic-react/src/webchat/input-panel/emoji-picker.tsx
  packages/botonic-react/src/webchat/input-panel/index.tsx
  packages/botonic-react/src/webchat/input-panel/persistent-menu.tsx
  packages/botonic-react/src/webchat/input-panel/send-button.tsx
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
  packages/botonic-react/src/webchat/message-list/index.tsx
  packages/botonic-react/src/webchat/message-list/intro-message.tsx
  packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx
  packages/botonic-react/src/webchat/message-list/use-notifications.ts
  packages/botonic-react/src/webchat/replies/index.tsx
  packages/botonic-react/src/webchat/session-view.jsx
  packages/botonic-react/src/webchat/trigger-button/index.tsx
  packages/botonic-react/src/webchat/webchat-dev.jsx
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/src/webchat/webview.jsx
  packages/botonic-react/tests/helpers/test-utils.jsx
  packages/botonic-react/tests/webchat/storage.test.jsx
  packages/botonic-react/tests/webchat/webchat.addmessages.test.jsx
  packages/botonic-react/tests/webchat/webchat.component.test.jsx
Labels: size/L

#2967 botonic-react: create webchat theme folder
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/index.ts
  packages/botonic-react/src/components/webchat-settings.tsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/util/webchat.ts
  packages/botonic-react/src/webchat-app.tsx
  packages/botonic-react/src/webchat/context/index.tsx
  packages/botonic-react/src/webchat/context/types.ts
  packages/botonic-react/src/webchat/context/use-webchat.ts
  packages/botonic-react/src/webchat/index-types.ts
  packages/botonic-react/src/webchat/input-panel/textarea.tsx
  packages/botonic-react/src/webchat/theme/types.ts
  packages/botonic-react/src/webchat/webchat.tsx
Labels: size/L

#2960 plugin-hubtype-analytics: add attributes in nlu events #BLT-1318
  CHANGELOG.md
  package-lock.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/user-input/intent.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-keyword.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-smart-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
  packages/botonic-plugin-hubtype-analytics/README.md
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
  packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
  packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
  packages/botonic-react/CHANGELOG.md
Labels: size/L

#2968 botonic-dx: use rspack as a bundler
  package-lock.json
  packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/.gitignore
  packages/botonic-dx-bundler-webpack/README.md
  packages/botonic-dx-bundler-webpack/baseline/babel.config.js
  packages/botonic-dx-bundler-webpack/baseline/webpack.config.js
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/CHANGELOG.md
  packages/botonic-dx/README.md
  packages/botonic-dx/baseline/prettier.config.js
  packages/botonic-dx/botonic-app-config/webpack/api-handlers.js
  packages/botonic-dx/botonic-app-config/webpack/api-rest.js
  packages/botonic-dx/botonic-app-config/webpack/api-ws.js
  packages/botonic-dx/botonic-app-config/webpack/assets-loaders.js
  packages/botonic-dx/botonic-app-config/webpack/optimization.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/babel-loader.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/esbuild-loader.js
  packages/botonic-dx/botonic-app-config/webpack/transpiling/transpiling-loader.js
  packages/botonic-dx/botonic-app-config/webpack/webchat.js
  packages/botonic-dx/package.json
  packages/botonic-dx/sample-config/.eslintrc-ci.js
  packages/botonic-dx/sample-config/.eslintrc.js
  packages/botonic-dx/sample-config/package.json
  packages/botonic-dx/sample-config/tsconfig.json
  packages/botonic-eslint-config/index.js
  packages/botonic-eslint-config/package.json
Labels: size/XXL

#2969 botonic: publish 0.31.0
  package-lock.json
  package.json
  packages/botonic-cli/package.json
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/README.md
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#2971 feat(botonic-dx): add babel config needed for jest
  package-lock.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/baseline/babel.config.js
  packages/botonic-dx/baseline/tsconfig.eslint.json
  packages/botonic-dx/baseline/tsconfig.tests.json
  packages/botonic-dx/package.json
Labels: size/M

#2970 botonic-cli & botonic-examples with version 0.31.0
  examples/blank-typescript/babel.config.js
  examples/blank-typescript/package.json
  examples/blank-typescript/rspack.config.ts
  examples/blank-typescript/tsconfig.json
  examples/blank/babel.config.js
  examples/blank/package.json
  examples/blank/rspack.config.ts
  examples/blank/tsconfig.json
  examples/blank/webpack.config.js
  examples/booking-platform/package.json
  examples/booking-platform/rspack.config.ts
  examples/booking-platform/src/webchat/rate-user-message.js
  examples/booking-platform/tsconfig.json
  examples/booking-platform/webpack.config.js
  examples/childs/package.json
  examples/childs/rspack.config.ts
  examples/childs/tsconfig.json
  examples/childs/webpack.config.js
  examples/custom-webchat/package.json
  examples/custom-webchat/rspack.config.ts
  examples/custom-webchat/src/webviews/my-webview.js
  examples/custom-webchat/tsconfig.json
  examples/custom-webchat/webpack.config.js
  examples/dynamic-carousel/package.json
  examples/dynamic-carousel/rspack.config.ts
  examples/dynamic-carousel/tsconfig.json
  examples/dynamic-carousel/webpack.config.js
  examples/dynamodb/package.json
  examples/dynamodb/rspack.config.ts
  examples/dynamodb/tsconfig.json
  examples/dynamodb/webpack.config.js
  examples/handoff/package.json
  examples/handoff/rspack.config.ts
  examples/handoff/tsconfig.json
  examples/handoff/webpack.config.js
  examples/intent/package.json
  examples/intent/rspack.config.ts
  examples/intent/tsconfig.json
  examples/intent/webpack.config.js
  examples/telco-offers/package.json
  examples/telco-offers/rspack.config.ts
  examples/telco-offers/tsconfig.json
  examples/telco-offers/webpack.config.js
  examples/tutorial/package.json
  examples/tutorial/rspack.config.ts
  examples/tutorial/tsconfig.json
  examples/tutorial/webpack.config.js
  package-lock.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-dx-bundler-webpack/package.json
Labels: size/XXL

#2965 React: use camelCase in component props
  package-lock.json
  packages/botonic-react/package.json
  packages/botonic-react/src/components/whatsapp-media-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-list.tsx
  packages/botonic-react/src/util/functional.ts
  packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
  packages/botonic-react/tests/utils.test.js
Labels: size/L

#2957 React/Core: added Whatsapp Product Carousel component to Botonic
  package-lock.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-react/package.json
  packages/botonic-react/src/components/index.ts
  packages/botonic-react/src/components/whatsapp-media-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-list.tsx
  packages/botonic-react/src/util/functional.ts
  packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap
  packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
  packages/botonic-react/tests/utils.test.js
Labels: size/L

#2956 React/Core: added Whatsapp Product List component to Botonic
  package-lock.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-react/src/components/index.ts
  packages/botonic-react/src/components/whatsapp-media-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-list.tsx
  packages/botonic-react/src/util/functional.ts
  packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product-list.test.jsx.snap
  packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
  packages/botonic-react/tests/utils.test.js
Labels: size/XL
