Repository hubtype/botonic, pull requests merged in 2025-02, with the labels that each got.

#2974 feat: add basic flow builder template in typescript
  examples/flow-builder-typescript/.eslintrc-ci.js
  examples/flow-builder-typescript/.eslintrc.js
  examples/flow-builder-typescript/.prettierrc.js
  examples/flow-builder-typescript/jest.config.js
  examples/flow-builder-typescript/jest.setup.js
  examples/flow-builder-typescript/package-lock.json
  examples/flow-builder-typescript/package.json
  examples/flow-builder-typescript/rspack-entries/dev-entry.ts
  examples/flow-builder-typescript/rspack-entries/node-entry.ts
  examples/flow-builder-typescript/rspack-entries/webchat-entry.ts
  examples/flow-builder-typescript/rspack-entries/webviews-entry.ts
  examples/flow-builder-typescript/rspack.config.ts
  examples/flow-builder-typescript/src/client/assets/.gitkeep
  examples/flow-builder-typescript/src/client/webchat/index.ts
  examples/flow-builder-typescript/src/client/webviews/index.ts
  examples/flow-builder-typescript/src/index.ts
  examples/flow-builder-typescript/src/server/actions/start-conversation.tsx
  examples/flow-builder-typescript/src/server/config.ts
  examples/flow-builder-typescript/src/server/constants.ts
  examples/flow-builder-typescript/src/server/domain/user-data.ts
  examples/flow-builder-typescript/src/server/plugins.ts
  examples/flow-builder-typescript/src/server/plugins/index.ts
  examples/flow-builder-typescript/src/server/routes.ts
  examples/flow-builder-typescript/src/server/tracking.ts
  examples/flow-builder-typescript/src/server/types.ts
  examples/flow-builder-typescript/src/server/utils/env-utils.ts
  examples/flow-builder-typescript/src/typings.d.ts
  examples/flow-builder-typescript/tsconfig.eslint.json
  examples/flow-builder-typescript/tsconfig.json
  examples/flow-builder-typescript/tsconfig.tests.json
Labels: size/XL

#2954 React/Core: added Whatsapp Catalog component to Botonic
  package-lock.json
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-react/src/components/index.ts
  packages/botonic-react/src/components/whatsapp-catalog.tsx
  packages/botonic-react/src/components/whatsapp-media-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-carousel.tsx
  packages/botonic-react/src/components/whatsapp-product-list.tsx
  packages/botonic-react/src/components/whatsapp-product.tsx
  packages/botonic-react/src/util/functional.ts
  packages/botonic-react/tests/components/__snapshots__/whatsapp-catalog.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product-list.test.jsx.snap
  packages/botonic-react/tests/components/__snapshots__/whatsapp-product.test.jsx.snap
  packages/botonic-react/tests/components/whatsapp-catalog.test.jsx
  packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
  packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
  packages/botonic-react/tests/components/whatsapp-product.test.jsx
  packages/botonic-react/tests/utils.test.js
Labels: size/XL

#2977 feat: avoid track FlowNode events for texts generated by knowledgebase
  package-lock.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
Labels: size/M

#2972 tech-feat: adapt botonic code to use new flow builder backend endpoints
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/webview/types.ts
  packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
Labels: size/M

#2975 feat: subscribe to initial queue position in botonic
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
  packages/botonic-core/src/models/legacy-types.ts
  packages/botonic-core/tests/handoff.test.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/handoff.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/knowledge-base.ts
  packages/botonic-react/package.json
Labels: size/M

#2980 release/0.32.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/package-lock.json
  examples/flow-builder-typescript/package.json
  examples/handoff/package.json
  examples/intent/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  package.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dialogflow/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-babel/package.json
  packages/botonic-plugin-inbenta/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-luis/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-plugin-watson/package.json
  packages/botonic-react/package.json
Labels: size/L

#2981 plugin-flow-builder: add final slash in flows url
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/index.ts
Labels: size/XS

#2982 botonic-react: carousel components with typescript
  packages/botonic-react/src/components/carousel.tsx
  packages/botonic-react/src/components/element.tsx
  packages/botonic-react/src/components/index-types.ts
  packages/botonic-react/src/components/pic.tsx
  packages/botonic-react/src/components/subtitle.tsx
  packages/botonic-react/src/components/title.tsx
Labels: size/L
