Repository hubtype/botonic, pull requests merged in 2025-08, with the labels that each got.

#3075 Feat: Improve plugin-ai-agent Typing for Cotext
  packages/botonic-plugin-ai-agents/src/types.ts
Labels: size/XS

#3077 botonic-react: input panel buttons no need enable attribute set to true to be used
  package-lock.json
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
  packages/botonic-react/src/webchat/input-panel/send-button.tsx
  packages/botonic-react/src/webchat/theme/default-theme.ts
Labels: size/S

#3083 plugin-ai-agents & plugin-flow-builder: create InferenceResponse for ai-agents #BLT-1803
  .github/workflows/botonic-ci-test-all-packages.yml
  .github/workflows/botonic-plugin-ai-agents.yml
  packages/botonic-plugin-ai-agents/babel.config.js
  packages/botonic-plugin-ai-agents/jest.config.js
  packages/botonic-plugin-ai-agents/jest.setup.js
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/index.ts
  packages/botonic-plugin-ai-agents/src/runner.ts
  packages/botonic-plugin-ai-agents/src/types.ts
  packages/botonic-plugin-ai-agents/tests/agent-builder.test.ts
  packages/botonic-plugin-ai-agents/tests/runner.test.ts
  packages/botonic-plugin-ai-agents/tsconfig.tests.json
  packages/botonic-plugin-flow-builder/src/action/ai-agent.ts
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/ai-agent.ts
Labels: size/L

#3087 refactor: create hubtype-analytics interfaces and enums in @botonic/core #BLT-1806
  packages/botonic-core/src/models/hubtype-analytics.ts
  packages/botonic-core/src/models/index.ts
  packages/botonic-plugin-flow-builder/src/action/fallback.ts
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
  packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-rating.test.ts
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-react/src/webchat/tracking.ts
Labels: size/XL

#3089 Fix: Use only last message on guardrail
  packages/botonic-plugin-ai-agents/src/guardrails/input.ts
  packages/botonic-plugin-ai-agents/tests/guardrails/input.test.ts
Labels: size/M

#3088 plugin-knowledge-bases and plugin-ai-agents types in core
  packages/botonic-core/src/models/ai-agents.ts
  packages/botonic-core/src/models/events/base-event.ts
  packages/botonic-core/src/models/events/botonic-event.ts
  packages/botonic-core/src/models/events/connections/connection-event.ts
  packages/botonic-core/src/models/events/connections/index.ts
  packages/botonic-core/src/models/events/index.ts
  packages/botonic-core/src/models/events/message/buttons.ts
  packages/botonic-core/src/models/events/message/carousel.ts
  packages/botonic-core/src/models/events/message/contact.ts
  packages/botonic-core/src/models/events/message/custom.ts
  packages/botonic-core/src/models/events/message/form.ts
  packages/botonic-core/src/models/events/message/index.ts
  packages/botonic-core/src/models/events/message/location.ts
  packages/botonic-core/src/models/events/message/media.ts
  packages/botonic-core/src/models/events/message/message-event.ts
  packages/botonic-core/src/models/events/message/missed.ts
  packages/botonic-core/src/models/events/message/postback.ts
  packages/botonic-core/src/models/events/message/replies.ts
  packages/botonic-core/src/models/events/message/text.ts
  packages/botonic-core/src/models/index.ts
  packages/botonic-core/src/models/knowledge-bases.ts
  packages/botonic-core/src/models/user.ts
  packages/botonic-plugin-ai-agents/src/structured-output/carousel.ts
  packages/botonic-plugin-ai-agents/src/structured-output/exit.ts
  packages/botonic-plugin-ai-agents/src/structured-output/index.ts
  packages/botonic-plugin-ai-agents/src/structured-output/shared.ts
  packages/botonic-plugin-ai-agents/src/structured-output/text-with-buttons.ts
  packages/botonic-plugin-ai-agents/src/structured-output/text.ts
  packages/botonic-plugin-ai-agents/src/types.ts
  packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
  packages/botonic-plugin-flow-builder/src/types.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/ai-agent.ts
  packages/botonic-plugin-flow-builder/tests/__mocks__/knowledge-base.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
  packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
  packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
  packages/botonic-plugin-knowledge-bases/src/index.ts
  packages/botonic-plugin-knowledge-bases/src/types.ts
Labels: size/XL

#3092 feat: change do-nothing payload #BLT-1830
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
Labels: size/S

#3081 plugin-flow-builder: not respond with first interaction if it receive a contentID #BLT-1788
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
Labels: size/M

#3090 chore: update CHANGELOGs and publish alpha versions
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/package-lock.json
  examples/flow-builder-typescript/package.json
  examples/flow-builder-typescript/src/server/plugins.ts
  examples/handoff/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  package.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-ai-agents/CHANGELOG.md
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/ai-agent.ts
  packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-hubtype-analytics/src/types.ts
  packages/botonic-plugin-knowledge-bases/CHANGELOG.md
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
Labels: size/L

#3093 fix(plugin-flow-builder): Fix payload in toBotonic method of FlowWhatsappButtonList
  package-lock.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
Labels: size/S

#3094 FlowBuilder: Export function to obtain the rating value selected
  package-lock.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/types.ts
Labels: size/M
