Repository hubtype/botonic, pull requests merged in 2025-09, with the labels that each got.

#3095 feat: add HtWeviewNode and resolve buttons with a webview target #BLT-1839
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-webview.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/webview.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/webview.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-text.test.ts
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/src/dev-app.jsx
  packages/botonic-react/src/index-types.ts
  packages/botonic-react/src/webchat/context/types.ts
  packages/botonic-react/src/webchat/context/use-webchat.ts
  packages/botonic-react/src/webchat/context/webchat-reducer.ts
  packages/botonic-react/src/webchat/webchat-dev.jsx
  packages/botonic-react/src/webchat/webchat.tsx
  packages/botonic-react/src/webchat/webview/index.tsx
  packages/botonic-react/tests/webchat/webchat.component.test.jsx
Labels: size/XL

#3096 botonic-cli & dx-bundler-rspack: change how bot config is created and cli read it #BLT-1878
  packages/botonic-cli/CHANGELOG.md
  packages/botonic-cli/src/util/bot-config.ts
  packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts
Labels: size/M

#3097 feat: add provider_id to get webview contents
  packages/botonic-plugin-flow-builder/src/webview/types.ts
  packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
Labels: size/XS

#3101 fix: payloads coming from AI Agents structured outputs to work with current flow
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/src/models/ai-agents.ts
  packages/botonic-plugin-ai-agents/CHANGELOG.md
  packages/botonic-plugin-ai-agents/src/structured-output/carousel.ts
  packages/botonic-plugin-ai-agents/src/structured-output/text-with-buttons.ts
  packages/botonic-plugin-ai-agents/tests/agent-builder.test.ts
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/index.tsx
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/tests/ai-agent.test.ts
  packages/botonic-plugin-flow-builder/tests/whatsapp-payload-conversion.test.ts
  packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
Labels: size/L

#3102 release/v0.40.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/package.json
  examples/handoff/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  package.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-ai-agents/CHANGELOG.md
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/types.ts
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
Labels: size/L
