Repository hubtype/botonic, pull requests merged in 2025-07, with the labels that each got.

#3053 style(core): Add missing salesforce attribute inside Input.context type
  packages/botonic-core/src/models/legacy-types.ts
Labels: size/XS

#3055 fix(react): Fix type of user argument in updateUser function
  packages/botonic-react/src/webchat/context/types.ts
Labels: size/XS

#3062 Refactor: AI Agent plugin reorganized
  package-lock.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/agent-builder.ts
  packages/botonic-plugin-ai-agents/src/index.ts
  packages/botonic-plugin-ai-agents/src/openai.ts
  packages/botonic-plugin-ai-agents/src/runner.ts
  packages/botonic-plugin-ai-agents/src/tools/index.ts
  packages/botonic-plugin-ai-agents/src/types.ts
Labels: size/L

#3063 plugin-flow-builder: rating flow #BLT-1745
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/src/action/payload.ts
  packages/botonic-plugin-flow-builder/src/api.ts
  packages/botonic-plugin-flow-builder/src/constants.ts
  packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/flow-rating.tsx
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
  packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/rating.ts
  packages/botonic-plugin-flow-builder/src/content-fields/index.ts
  packages/botonic-plugin-flow-builder/src/index.ts
  packages/botonic-plugin-flow-builder/src/tracking.ts
  packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
  packages/botonic-plugin-flow-builder/tests/helpers/flows/rating.ts
  packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-rating.test.ts
  packages/botonic-plugin-flow-builder/tests/messages/flow-text.test.ts
Labels: size/XL

#3067 Fix: CustomTool Typing + Increase Memory Length
  package-lock.json
  package.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-ai-agents/src/index.ts
  packages/botonic-plugin-ai-agents/src/openai.ts
  packages/botonic-plugin-ai-agents/src/runner.ts
  packages/botonic-plugin-ai-agents/src/types.ts
Labels: size/S

#3068 botonic-core: store case rating in test integrations #BLT-1772
  package-lock.json
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-core/src/handoff.ts
Labels: size/XS

#3069 Release 0.37.0
  examples/blank-typescript/package.json
  examples/blank/package.json
  examples/booking-platform/package.json
  examples/childs/package.json
  examples/custom-webchat/package.json
  examples/dynamic-carousel/package.json
  examples/dynamodb/package.json
  examples/flow-builder-typescript/.env.template
  examples/flow-builder-typescript/package-lock.json
  examples/flow-builder-typescript/package.json
  examples/flow-builder-typescript/rspack.config.ts
  examples/flow-builder-typescript/src/bot-config.ts
  examples/flow-builder-typescript/src/client/webchat/index.ts
  examples/flow-builder-typescript/src/server/config.ts
  examples/flow-builder-typescript/src/server/plugins.ts
  examples/flow-builder-typescript/src/server/plugins/index.ts
  examples/flow-builder-typescript/src/server/tools.ts
  examples/flow-builder-typescript/src/server/utils/env-utils.ts
  examples/handoff/package.json
  examples/telco-offers/package.json
  examples/tutorial/package.json
  package-lock.json
  package.json
  packages/botonic-cli/README.md
  packages/botonic-cli/package.json
  packages/botonic-cli/src/botonic-examples.ts
  packages/botonic-cli/src/util/bot-config.ts
  packages/botonic-core/CHANGELOG.md
  packages/botonic-core/package.json
  packages/botonic-dx-bundler-rspack/package.json
  packages/botonic-dx-bundler-webpack/package.json
  packages/botonic-dx/package.json
  packages/botonic-eslint-config/package.json
  packages/botonic-plugin-ai-agents/package.json
  packages/botonic-plugin-contentful/package.json
  packages/botonic-plugin-dashbot/package.json
  packages/botonic-plugin-dynamodb/package.json
  packages/botonic-plugin-flow-builder/CHANGELOG.md
  packages/botonic-plugin-flow-builder/README.md
  packages/botonic-plugin-flow-builder/package.json
  packages/botonic-plugin-google-analytics/package.json
  packages/botonic-plugin-google-translation/package.json
  packages/botonic-plugin-google-translation/src/index.ts
  packages/botonic-plugin-google-translation/src/options.ts
  packages/botonic-plugin-hubtype-analytics/package.json
  packages/botonic-plugin-knowledge-bases/package.json
  packages/botonic-plugin-segment/package.json
  packages/botonic-react/CHANGELOG.md
  packages/botonic-react/package.json
Labels: size/L

#3071 dx-bundler-rspack: bump @rspack dependencies to ^1.4.x
  package-lock.json
  packages/botonic-dx-bundler-rspack/package.json
Labels: size/S
